// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="filter_accel,hls_ip_2019_2_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xczu3eg-sbva484-1-e,HLS_INPUT_CLOCK=3.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.846000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=22,HLS_SYN_FF=3216,HLS_SYN_LUT=2526,HLS_VERSION=2019_2_1}" *)

module filter_accel (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in0,
        in1,
        in2,
        in3,
        in4,
        in5,
        in6,
        in7,
        in8,
        in9,
        in10,
        in11,
        in12,
        in13,
        in14,
        in15,
        in16,
        out_r,
        out_r_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] in0;
input  [7:0] in1;
input  [7:0] in2;
input  [7:0] in3;
input  [7:0] in4;
input  [7:0] in5;
input  [7:0] in6;
input  [7:0] in7;
input  [7:0] in8;
input  [7:0] in9;
input  [7:0] in10;
input  [7:0] in11;
input  [7:0] in12;
input  [7:0] in13;
input  [7:0] in14;
input  [7:0] in15;
input  [7:0] in16;
output  [31:0] out_r;
output   out_r_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg out_r_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [22:0] sum_l3_0;
reg   [22:0] sum_l3_1;
reg   [21:0] sum_l2_0_0;
reg   [21:0] sum_l2_0_1;
reg   [21:0] sum_l2_1_0;
reg   [21:0] sum_l2_1_1;
reg   [20:0] sum_l1_0_0;
reg   [20:0] sum_l1_0_1;
reg   [20:0] sum_l1_0_2;
reg   [19:0] sum_l1_0_3;
reg   [19:0] sum_l1_1_0;
reg   [20:0] sum_l1_1_1;
reg   [19:0] sum_l1_1_2;
reg   [20:0] sum_l1_1_3;
reg   [19:0] sum_l0_0_0;
reg   [18:0] sum_l0_1_0;
reg   [19:0] sum_l0_0_1;
reg   [17:0] sum_l0_1_1;
reg   [19:0] sum_l0_0_2;
reg   [16:0] sum_l0_1_2;
reg   [18:0] sum_l0_0_3;
reg   [17:0] sum_l0_1_3;
reg   [17:0] sum_l0_2_0;
reg   [18:0] sum_l0_3_0;
reg   [17:0] sum_l0_2_1;
reg   [18:0] sum_l0_3_1;
reg   [16:0] sum_l0_2_2;
reg   [18:0] sum_l0_3_2;
reg   [17:0] sum_l0_2_3;
reg   [19:0] sum_l0_3_3;
reg   [18:0] prod_0_0;
reg   [17:0] prod_1_0;
reg   [18:0] prod_0_1;
reg   [18:0] prod_1_1;
reg   [18:0] prod_0_2;
reg   [18:0] prod_1_2;
reg   [18:0] prod_0_3;
reg   [17:0] prod_1_3;
reg   [17:0] prod_2_0;
reg   [17:0] prod_3_0;
reg   [16:0] prod_2_1;
reg   [15:0] prod_3_1;
reg   [16:0] prod_2_2;
reg   [13:0] prod_3_2;
reg   [17:0] prod_2_3;
reg   [15:0] prod_3_3;
reg   [15:0] prod_4_0;
reg   [17:0] prod_5_0;
reg   [13:0] prod_4_1;
reg   [17:0] prod_5_1;
reg   [15:0] prod_4_2;
reg   [16:0] prod_5_2;
reg   [17:0] prod_4_3;
reg   [18:0] prod_5_3;
reg   [17:0] prod_6_0;
reg   [18:0] prod_7_0;
reg   [18:0] prod_6_1;
reg   [17:0] prod_7_1;
reg   [17:0] prod_6_2;
reg   [18:0] prod_7_2;
reg   [18:0] prod_6_3;
reg   [17:0] prod_7_3;
reg   [10:0] reg2_0_0;
reg   [10:0] reg2_0_1;
reg   [10:0] reg2_0_2;
reg   [10:0] reg2_0_3;
reg   [10:0] reg2_1_0;
reg   [10:0] reg2_1_1;
reg   [10:0] reg2_1_2;
reg   [10:0] reg2_1_3;
reg   [10:0] reg2_2_0;
reg   [10:0] reg2_2_1;
reg   [10:0] reg2_2_2;
reg   [9:0] reg2_2_3;
reg   [10:0] reg2_3_0;
reg   [10:0] reg2_3_1;
reg   [10:0] reg2_3_2;
reg   [10:0] reg2_3_3;
reg   [10:0] reg2_4_0;
reg   [9:0] reg2_4_1;
reg   [10:0] reg2_4_2;
reg   [10:0] reg2_4_3;
reg   [10:0] reg2_5_0;
reg   [10:0] reg2_5_1;
reg   [9:0] reg2_5_2;
reg   [10:0] reg2_5_3;
reg   [10:0] reg2_6_0;
reg   [10:0] reg2_6_1;
reg   [9:0] reg2_6_2;
reg   [10:0] reg2_6_3;
reg   [10:0] reg2_7_0;
reg   [9:0] reg2_7_1;
reg   [10:0] reg2_7_2;
reg   [8:0] reg2_7_3;
reg   [8:0] reg1_0_8;
reg   [9:0] reg1_8_0;
reg   [9:0] reg1_1_5;
reg   [9:0] reg1_5_1;
reg   [9:0] reg1_1_6;
reg   [9:0] reg1_6_1;
reg   [9:0] reg1_1_7;
reg   [9:0] reg1_7_1;
reg   [8:0] reg1_1_8;
reg   [9:0] reg1_8_1;
reg   [9:0] reg1_2_3;
reg   [9:0] reg1_3_2;
reg   [9:0] reg1_2_4;
reg   [9:0] reg1_4_2;
reg   [9:0] reg1_2_5;
reg   [9:0] reg1_5_2;
reg   [9:0] reg1_2_6;
reg   [9:0] reg1_6_2;
reg   [9:0] reg1_2_7;
reg   [9:0] reg1_7_2;
reg   [8:0] reg1_2_8;
reg   [9:0] reg1_8_2;
reg   [9:0] reg1_3_3;
reg   [9:0] reg1_3_4;
reg   [9:0] reg1_4_3;
reg   [9:0] reg1_3_5;
reg   [9:0] reg1_5_3;
reg   [9:0] reg1_3_6;
reg   [9:0] reg1_6_3;
reg   [9:0] reg1_3_7;
reg   [9:0] reg1_7_3;
reg   [8:0] reg1_3_8;
reg   [9:0] reg1_8_3;
reg   [9:0] reg1_4_4;
reg   [9:0] reg1_4_5;
reg   [9:0] reg1_5_4;
reg   [9:0] reg1_4_6;
reg   [9:0] reg1_6_4;
reg   [9:0] reg1_4_7;
reg   [9:0] reg1_7_4;
reg   [8:0] reg1_4_8;
reg   [9:0] reg1_8_4;
reg   [9:0] reg1_5_5;
reg   [9:0] reg1_5_6;
reg   [9:0] reg1_6_5;
reg   [9:0] reg1_5_7;
reg   [9:0] reg1_7_5;
reg   [8:0] reg1_5_8;
reg   [9:0] reg1_8_5;
reg   [9:0] reg1_6_6;
reg   [9:0] reg1_6_7;
reg   [9:0] reg1_7_6;
reg   [8:0] reg1_6_8;
reg   [9:0] reg1_8_6;
reg   [9:0] reg1_7_7;
reg   [8:0] reg1_7_8;
reg   [9:0] reg1_8_7;
reg   [8:0] reg1_8_8;
reg   [8:0] reg0_0_0;
reg   [8:0] reg0_0_1;
reg   [8:0] reg0_0_2;
reg   [8:0] reg0_0_3;
reg   [8:0] reg0_0_4;
reg   [8:0] reg0_0_5;
reg   [8:0] reg0_0_6;
reg   [8:0] reg0_0_7;
reg   [8:0] reg0_0_8;
reg   [8:0] reg0_1_0;
reg   [8:0] reg0_1_1;
reg   [8:0] reg0_1_2;
reg   [8:0] reg0_1_3;
reg   [8:0] reg0_1_4;
reg   [8:0] reg0_1_5;
reg   [8:0] reg0_1_11;
reg   [8:0] reg0_1_6;
reg   [8:0] reg0_1_10;
reg   [8:0] reg0_1_7;
reg   [8:0] reg0_1_9;
reg   [8:0] reg0_1_8;
reg   [8:0] reg0_2_0;
reg   [8:0] reg0_2_1;
reg   [8:0] reg0_2_2;
reg   [8:0] reg0_2_3;
reg   [8:0] reg0_2_13;
reg   [8:0] reg0_2_4;
reg   [8:0] reg0_2_12;
reg   [8:0] reg0_2_5;
reg   [8:0] reg0_2_11;
reg   [8:0] reg0_2_6;
reg   [8:0] reg0_2_10;
reg   [8:0] reg0_2_7;
reg   [8:0] reg0_2_9;
reg   [8:0] reg0_2_8;
reg   [8:0] reg0_3_0;
reg   [8:0] reg0_3_1;
reg   [8:0] reg0_3_2;
reg   [8:0] reg0_3_14;
reg   [8:0] reg0_3_3;
reg   [8:0] reg0_3_13;
reg   [8:0] reg0_3_4;
reg   [8:0] reg0_3_12;
reg   [8:0] reg0_3_5;
reg   [8:0] reg0_3_11;
reg   [8:0] reg0_3_6;
reg   [8:0] reg0_3_10;
reg   [8:0] reg0_3_7;
reg   [8:0] reg0_3_9;
reg   [8:0] reg0_3_8;
reg   [8:0] reg0_4_0;
reg   [8:0] reg0_4_1;
reg   [8:0] reg0_4_2;
reg   [8:0] reg0_4_14;
reg   [8:0] reg0_4_3;
reg   [8:0] reg0_4_13;
reg   [8:0] reg0_4_4;
reg   [8:0] reg0_4_12;
reg   [8:0] reg0_4_5;
reg   [8:0] reg0_4_11;
reg   [8:0] reg0_4_6;
reg   [8:0] reg0_4_10;
reg   [8:0] reg0_4_7;
reg   [8:0] reg0_4_9;
reg   [8:0] reg0_4_8;
reg   [8:0] reg0_5_0;
reg   [8:0] reg0_5_1;
reg   [8:0] reg0_5_15;
reg   [8:0] reg0_5_2;
reg   [8:0] reg0_5_14;
reg   [8:0] reg0_5_3;
reg   [8:0] reg0_5_13;
reg   [8:0] reg0_5_4;
reg   [8:0] reg0_5_12;
reg   [8:0] reg0_5_5;
reg   [8:0] reg0_5_11;
reg   [8:0] reg0_5_6;
reg   [8:0] reg0_5_10;
reg   [8:0] reg0_5_7;
reg   [8:0] reg0_5_9;
reg   [8:0] reg0_5_8;
reg   [8:0] reg0_6_0;
reg   [8:0] reg0_6_1;
reg   [8:0] reg0_6_15;
reg   [8:0] reg0_6_2;
reg   [8:0] reg0_6_14;
reg   [8:0] reg0_6_3;
reg   [8:0] reg0_6_13;
reg   [8:0] reg0_6_4;
reg   [8:0] reg0_6_12;
reg   [8:0] reg0_6_5;
reg   [8:0] reg0_6_11;
reg   [8:0] reg0_6_6;
reg   [8:0] reg0_6_10;
reg   [8:0] reg0_6_7;
reg   [8:0] reg0_6_9;
reg   [8:0] reg0_6_8;
reg   [8:0] reg0_7_0;
reg   [8:0] reg0_7_1;
reg   [8:0] reg0_7_15;
reg   [8:0] reg0_7_2;
reg   [8:0] reg0_7_14;
reg   [8:0] reg0_7_3;
reg   [8:0] reg0_7_13;
reg   [8:0] reg0_7_4;
reg   [8:0] reg0_7_12;
reg   [8:0] reg0_7_5;
reg   [8:0] reg0_7_11;
reg   [8:0] reg0_7_6;
reg   [8:0] reg0_7_10;
reg   [8:0] reg0_7_7;
reg   [8:0] reg0_7_9;
reg   [8:0] reg0_7_8;
reg   [7:0] reg0_8_0;
reg   [8:0] reg0_8_16;
reg   [7:0] reg0_8_1;
reg   [8:0] reg0_8_15;
reg   [7:0] reg0_8_2;
reg   [8:0] reg0_8_14;
reg   [7:0] reg0_8_3;
reg   [8:0] reg0_8_13;
reg   [8:0] reg0_8_4;
reg   [8:0] reg0_8_12;
reg   [8:0] reg0_8_5;
reg   [8:0] reg0_8_11;
reg   [8:0] reg0_8_6;
reg   [8:0] reg0_8_10;
reg   [8:0] reg0_8_7;
reg   [8:0] reg0_8_9;
reg   [8:0] reg0_8_8;
wire   [22:0] add_ln52_fu_840_p2;
wire   [22:0] add_ln52_1_fu_868_p2;
wire   [21:0] add_ln60_fu_896_p2;
wire   [21:0] add_ln60_1_fu_924_p2;
wire   [21:0] add_ln60_2_fu_952_p2;
wire   [21:0] add_ln60_3_fu_980_p2;
wire   [20:0] add_ln69_fu_1008_p2;
wire   [20:0] add_ln69_1_fu_1036_p2;
wire   [20:0] add_ln69_2_fu_1064_p2;
wire   [19:0] add_ln69_3_fu_1092_p2;
wire   [19:0] add_ln69_4_fu_1120_p2;
wire   [20:0] add_ln69_5_fu_1148_p2;
wire   [19:0] add_ln69_6_fu_1176_p2;
wire   [20:0] add_ln69_7_fu_1204_p2;
wire   [19:0] add_ln78_fu_1232_p2;
wire   [18:0] add_ln78_4_fu_1340_p2;
wire   [19:0] add_ln78_1_fu_1260_p2;
wire   [17:0] add_ln78_5_fu_1368_p2;
wire   [19:0] add_ln78_2_fu_1288_p2;
wire   [16:0] add_ln78_6_fu_1392_p2;
wire   [18:0] add_ln78_3_fu_1312_p2;
wire   [17:0] add_ln78_7_fu_1416_p2;
wire   [17:0] add_ln78_8_fu_1440_p2;
wire   [18:0] add_ln78_12_fu_1536_p2;
wire   [17:0] add_ln78_9_fu_1464_p2;
wire   [18:0] add_ln78_13_fu_1560_p2;
wire   [16:0] add_ln78_10_fu_1488_p2;
wire   [18:0] add_ln78_14_fu_1584_p2;
wire   [17:0] add_ln78_11_fu_1512_p2;
wire   [19:0] add_ln78_15_fu_1612_p2;
wire  signed [18:0] mul_ln86_fu_5510_p2;
wire   [17:0] sub_ln86_fu_1692_p2;
wire  signed [18:0] mul_ln86_1_fu_5517_p2;
wire  signed [18:0] mul_ln86_4_fu_5538_p2;
wire  signed [18:0] mul_ln86_2_fu_5524_p2;
wire  signed [18:0] mul_ln86_5_fu_5545_p2;
wire  signed [18:0] mul_ln86_3_fu_5531_p2;
wire  signed [17:0] mul_ln86_6_fu_5552_p2;
wire   [17:0] sub_ln86_2_fu_1781_p2;
wire  signed [17:0] mul_ln86_10_fu_5580_p2;
wire  signed [16:0] mul_ln86_7_fu_5559_p2;
wire   [15:0] sub_ln86_7_fu_1865_p2;
wire  signed [16:0] mul_ln86_8_fu_5566_p2;
wire   [13:0] sub_ln86_3_fu_1897_p2;
wire  signed [17:0] mul_ln86_9_fu_5573_p2;
wire   [15:0] sub_ln86_4_fu_1937_p2;
wire   [15:0] add_ln86_fu_1977_p2;
wire   [17:0] mul_ln86_12_fu_5594_p2;
wire   [13:0] sub_ln86_5_fu_2005_p2;
wire   [17:0] mul_ln86_13_fu_5601_p2;
wire   [15:0] add_ln86_1_fu_2045_p2;
wire   [16:0] mul_ln86_14_fu_5608_p2;
wire   [17:0] mul_ln86_11_fu_5587_p2;
wire   [18:0] mul_ln86_15_fu_5615_p2;
wire   [17:0] add_ln86_2_fu_2150_p2;
wire   [18:0] mul_ln86_19_fu_5643_p2;
wire   [18:0] mul_ln86_16_fu_5622_p2;
wire   [17:0] mul_ln86_20_fu_5650_p2;
wire   [17:0] mul_ln86_17_fu_5629_p2;
wire   [18:0] mul_ln86_21_fu_5657_p2;
wire   [18:0] mul_ln86_18_fu_5636_p2;
wire   [17:0] sub_ln86_6_fu_2260_p2;
wire   [10:0] add_ln90_fu_2288_p2;
wire   [10:0] add_ln91_fu_2316_p2;
wire   [10:0] add_ln92_fu_2344_p2;
wire   [10:0] add_ln93_fu_2372_p2;
wire   [10:0] add_ln94_fu_2400_p2;
wire   [10:0] add_ln95_fu_2428_p2;
wire   [10:0] add_ln96_fu_2456_p2;
wire   [10:0] add_ln97_fu_2484_p2;
wire   [10:0] add_ln98_fu_2512_p2;
wire   [10:0] add_ln99_fu_2540_p2;
wire   [10:0] add_ln100_fu_2568_p2;
wire   [10:0] add_ln102_fu_2606_p2;
wire   [10:0] add_ln103_fu_2634_p2;
wire   [10:0] add_ln104_fu_2662_p2;
wire   [10:0] add_ln105_fu_2690_p2;
wire   [10:0] add_ln106_fu_2718_p2;
wire   [10:0] add_ln108_fu_2756_p2;
wire   [10:0] add_ln109_fu_2784_p2;
wire   [10:0] add_ln110_fu_2812_p2;
wire   [10:0] add_ln111_fu_2840_p2;
wire   [10:0] add_ln113_fu_2878_p2;
wire   [10:0] add_ln114_fu_2906_p2;
wire   [10:0] add_ln115_fu_2934_p2;
wire   [10:0] add_ln117_fu_2972_p2;
wire   [10:0] add_ln118_fu_3000_p2;
wire   [10:0] add_ln120_fu_3038_p2;
wire   [9:0] add_ln125_fu_4396_p2;
wire   [9:0] add_ln130_fu_3138_p2;
wire   [9:0] add_ln126_fu_3770_p2;
wire   [9:0] add_ln131_fu_3166_p2;
wire   [9:0] add_ln126_1_fu_3980_p2;
wire   [9:0] add_ln132_fu_3194_p2;
wire   [9:0] add_ln126_2_fu_4190_p2;
wire   [9:0] add_ln126_3_fu_4424_p2;
wire   [9:0] add_ln128_fu_3244_p2;
wire   [9:0] add_ln127_fu_3402_p2;
wire   [9:0] add_ln129_fu_3272_p2;
wire   [9:0] add_ln127_1_fu_3588_p2;
wire   [9:0] add_ln130_1_fu_3300_p2;
wire   [9:0] add_ln127_2_fu_3798_p2;
wire   [9:0] add_ln131_1_fu_3328_p2;
wire   [9:0] add_ln127_3_fu_4008_p2;
wire   [9:0] add_ln132_1_fu_3356_p2;
wire   [9:0] add_ln127_4_fu_4218_p2;
wire   [9:0] add_ln127_5_fu_4452_p2;
wire   [9:0] add_ln128_1_fu_3430_p2;
wire   [9:0] add_ln129_1_fu_3458_p2;
wire   [9:0] add_ln128_2_fu_3616_p2;
wire   [9:0] add_ln130_2_fu_3486_p2;
wire   [9:0] add_ln128_3_fu_3826_p2;
wire   [9:0] add_ln131_2_fu_3514_p2;
wire   [9:0] add_ln128_4_fu_4036_p2;
wire   [9:0] add_ln132_2_fu_3542_p2;
wire   [9:0] add_ln128_5_fu_4246_p2;
wire   [9:0] add_ln128_6_fu_4484_p2;
wire   [9:0] add_ln129_2_fu_3644_p2;
wire   [9:0] add_ln130_3_fu_3672_p2;
wire   [9:0] add_ln129_3_fu_3854_p2;
wire   [9:0] add_ln131_3_fu_3700_p2;
wire   [9:0] add_ln129_4_fu_4064_p2;
wire   [9:0] add_ln132_3_fu_3728_p2;
wire   [9:0] add_ln129_5_fu_4274_p2;
wire   [9:0] add_ln129_6_fu_4512_p2;
wire   [9:0] add_ln130_4_fu_3882_p2;
wire   [9:0] add_ln131_4_fu_3910_p2;
wire   [9:0] add_ln130_5_fu_4092_p2;
wire   [9:0] add_ln132_4_fu_3938_p2;
wire   [9:0] add_ln130_6_fu_4302_p2;
wire   [9:0] add_ln130_7_fu_4540_p2;
wire   [9:0] add_ln131_5_fu_4120_p2;
wire   [9:0] add_ln132_5_fu_4148_p2;
wire   [9:0] add_ln131_6_fu_4330_p2;
wire   [9:0] add_ln131_7_fu_4568_p2;
wire   [9:0] add_ln132_6_fu_4358_p2;
wire   [9:0] add_ln132_7_fu_4596_p2;
wire   [8:0] add_ln144_fu_5352_p2;
wire   [8:0] add_ln145_fu_5372_p2;
wire   [8:0] add_ln146_fu_5392_p2;
wire   [8:0] add_ln147_fu_5412_p2;
wire   [8:0] add_ln148_fu_5432_p2;
wire   [8:0] add_ln149_fu_5452_p2;
wire   [8:0] add_ln150_fu_5472_p2;
wire   [8:0] add_ln151_fu_5492_p2;
wire   [8:0] zext_ln128_14_fu_4468_p1;
wire  signed [22:0] sext_ln47_fu_801_p0;
wire  signed [22:0] sext_ln47_1_fu_809_p0;
wire  signed [23:0] sext_ln47_1_fu_809_p1;
wire  signed [23:0] sext_ln47_fu_801_p1;
wire   [23:0] add_ln47_fu_813_p2;
wire  signed [21:0] sext_ln52_fu_828_p0;
wire  signed [21:0] sext_ln52_1_fu_836_p0;
wire  signed [22:0] sext_ln52_fu_828_p1;
wire  signed [22:0] sext_ln52_1_fu_836_p1;
wire  signed [21:0] sext_ln52_2_fu_856_p0;
wire  signed [21:0] sext_ln52_3_fu_864_p0;
wire  signed [22:0] sext_ln52_2_fu_856_p1;
wire  signed [22:0] sext_ln52_3_fu_864_p1;
wire  signed [20:0] sext_ln60_fu_884_p0;
wire  signed [20:0] sext_ln60_1_fu_892_p0;
wire  signed [21:0] sext_ln60_fu_884_p1;
wire  signed [21:0] sext_ln60_1_fu_892_p1;
wire  signed [20:0] sext_ln60_2_fu_912_p0;
wire  signed [19:0] sext_ln60_3_fu_920_p0;
wire  signed [21:0] sext_ln60_2_fu_912_p1;
wire  signed [21:0] sext_ln60_3_fu_920_p1;
wire  signed [20:0] sext_ln60_4_fu_948_p0;
wire   [21:0] zext_ln60_fu_940_p1;
wire  signed [21:0] sext_ln60_4_fu_948_p1;
wire  signed [20:0] sext_ln60_5_fu_976_p0;
wire   [21:0] zext_ln60_1_fu_968_p1;
wire  signed [21:0] sext_ln60_5_fu_976_p1;
wire  signed [19:0] sext_ln69_fu_996_p0;
wire  signed [18:0] sext_ln69_1_fu_1004_p0;
wire  signed [20:0] sext_ln69_fu_996_p1;
wire  signed [20:0] sext_ln69_1_fu_1004_p1;
wire  signed [19:0] sext_ln69_2_fu_1024_p0;
wire  signed [17:0] sext_ln69_3_fu_1032_p0;
wire  signed [20:0] sext_ln69_2_fu_1024_p1;
wire  signed [20:0] sext_ln69_3_fu_1032_p1;
wire  signed [19:0] sext_ln69_4_fu_1052_p0;
wire  signed [16:0] sext_ln69_5_fu_1060_p0;
wire  signed [20:0] sext_ln69_4_fu_1052_p1;
wire  signed [20:0] sext_ln69_5_fu_1060_p1;
wire  signed [18:0] sext_ln69_6_fu_1080_p0;
wire  signed [17:0] sext_ln69_7_fu_1088_p0;
wire  signed [19:0] sext_ln69_6_fu_1080_p1;
wire  signed [19:0] sext_ln69_7_fu_1088_p1;
wire   [19:0] zext_ln69_fu_1108_p1;
wire   [19:0] zext_ln69_1_fu_1116_p1;
wire  signed [17:0] sext_ln69_8_fu_1136_p0;
wire  signed [20:0] sext_ln69_8_fu_1136_p1;
wire   [20:0] zext_ln69_2_fu_1144_p1;
wire   [19:0] zext_ln69_3_fu_1164_p1;
wire   [19:0] zext_ln69_4_fu_1172_p1;
wire  signed [19:0] sext_ln69_9_fu_1200_p0;
wire   [20:0] zext_ln69_5_fu_1192_p1;
wire  signed [20:0] sext_ln69_9_fu_1200_p1;
wire  signed [18:0] sext_ln78_fu_1220_p0;
wire  signed [17:0] sext_ln78_1_fu_1228_p0;
wire  signed [19:0] sext_ln78_fu_1220_p1;
wire  signed [19:0] sext_ln78_1_fu_1228_p1;
wire  signed [18:0] sext_ln78_2_fu_1248_p0;
wire  signed [18:0] sext_ln78_3_fu_1256_p0;
wire  signed [19:0] sext_ln78_2_fu_1248_p1;
wire  signed [19:0] sext_ln78_3_fu_1256_p1;
wire  signed [18:0] sext_ln78_4_fu_1276_p0;
wire  signed [18:0] sext_ln78_5_fu_1284_p0;
wire  signed [19:0] sext_ln78_4_fu_1276_p1;
wire  signed [19:0] sext_ln78_5_fu_1284_p1;
wire  signed [17:0] sext_ln78_6_fu_1308_p0;
wire  signed [18:0] sext_ln78_6_fu_1308_p1;
wire  signed [17:0] sext_ln78_7_fu_1328_p0;
wire  signed [17:0] sext_ln78_8_fu_1336_p0;
wire  signed [18:0] sext_ln78_7_fu_1328_p1;
wire  signed [18:0] sext_ln78_8_fu_1336_p1;
wire  signed [16:0] sext_ln78_9_fu_1356_p0;
wire  signed [15:0] sext_ln78_10_fu_1364_p0;
wire  signed [17:0] sext_ln78_9_fu_1356_p1;
wire  signed [17:0] sext_ln78_10_fu_1364_p1;
wire  signed [13:0] sext_ln78_11_fu_1388_p0;
wire  signed [16:0] sext_ln78_11_fu_1388_p1;
wire  signed [15:0] sext_ln78_12_fu_1412_p0;
wire  signed [17:0] sext_ln78_12_fu_1412_p1;
wire   [17:0] zext_ln78_fu_1432_p1;
wire  signed [13:0] sext_ln78_13_fu_1456_p0;
wire  signed [17:0] sext_ln78_13_fu_1456_p1;
wire   [16:0] zext_ln78_1_fu_1480_p1;
wire   [17:0] trunc_ln78_fu_1508_p1;
wire   [18:0] zext_ln78_2_fu_1528_p1;
wire   [18:0] zext_ln78_3_fu_1556_p1;
wire   [18:0] zext_ln78_4_fu_1576_p1;
wire  signed [17:0] sext_ln78_14_fu_1608_p0;
wire   [19:0] zext_ln78_5_fu_1600_p1;
wire  signed [19:0] sext_ln78_14_fu_1608_p1;
wire   [16:0] shl_ln_fu_1680_p3;
wire   [17:0] zext_ln86_4_fu_1688_p1;
wire   [15:0] shl_ln86_1_fu_1747_p3;
wire   [16:0] zext_ln86_8_fu_1755_p1;
wire   [16:0] sub_ln86_1_fu_1759_p2;
wire   [12:0] shl_ln86_2_fu_1769_p3;
wire  signed [17:0] sext_ln86_fu_1765_p1;
wire   [17:0] zext_ln86_9_fu_1777_p1;
wire   [14:0] tmp_fu_1853_p3;
wire   [15:0] zext_ln86_14_fu_1849_p1;
wire   [15:0] zext_ln86_15_fu_1861_p1;
wire   [12:0] shl_ln86_3_fu_1885_p3;
wire   [13:0] zext_ln86_17_fu_1893_p1;
wire   [13:0] zext_ln86_16_fu_1881_p1;
wire   [14:0] shl_ln86_4_fu_1913_p3;
wire   [11:0] shl_ln86_5_fu_1925_p3;
wire   [15:0] zext_ln86_18_fu_1921_p1;
wire   [15:0] zext_ln86_19_fu_1933_p1;
wire   [14:0] shl_ln86_6_fu_1953_p3;
wire   [11:0] shl_ln86_7_fu_1965_p3;
wire   [15:0] zext_ln86_20_fu_1961_p1;
wire   [15:0] zext_ln86_21_fu_1973_p1;
wire   [12:0] shl_ln86_8_fu_1993_p3;
wire   [13:0] zext_ln86_22_fu_2001_p1;
wire   [14:0] shl_ln86_9_fu_2021_p3;
wire   [11:0] shl_ln86_s_fu_2033_p3;
wire   [15:0] zext_ln86_24_fu_2029_p1;
wire   [15:0] zext_ln86_26_fu_2041_p1;
wire   [16:0] shl_ln86_10_fu_2126_p3;
wire   [14:0] shl_ln86_11_fu_2138_p3;
wire   [17:0] zext_ln86_34_fu_2134_p1;
wire   [17:0] zext_ln86_35_fu_2146_p1;
wire   [15:0] tmp_1_fu_2248_p3;
wire   [17:0] zext_ln86_39_fu_2256_p1;
wire   [17:0] zext_ln86_38_fu_2244_p1;
wire   [10:0] zext_ln90_1_fu_2284_p1;
wire   [10:0] zext_ln90_fu_2276_p1;
wire   [10:0] zext_ln91_1_fu_2312_p1;
wire   [10:0] zext_ln91_fu_2304_p1;
wire   [10:0] zext_ln92_1_fu_2340_p1;
wire   [10:0] zext_ln92_fu_2332_p1;
wire   [10:0] zext_ln93_1_fu_2368_p1;
wire   [10:0] zext_ln93_fu_2360_p1;
wire   [10:0] zext_ln94_1_fu_2396_p1;
wire   [10:0] zext_ln94_fu_2388_p1;
wire   [10:0] zext_ln95_1_fu_2424_p1;
wire   [10:0] zext_ln95_fu_2416_p1;
wire   [10:0] zext_ln96_1_fu_2452_p1;
wire   [10:0] zext_ln96_fu_2444_p1;
wire   [10:0] zext_ln97_1_fu_2480_p1;
wire   [10:0] zext_ln97_fu_2472_p1;
wire   [10:0] zext_ln98_1_fu_2508_p1;
wire   [10:0] zext_ln98_fu_2500_p1;
wire   [10:0] zext_ln99_1_fu_2536_p1;
wire   [10:0] zext_ln99_fu_2528_p1;
wire   [10:0] zext_ln100_1_fu_2564_p1;
wire   [10:0] zext_ln100_fu_2556_p1;
wire   [10:0] zext_ln102_1_fu_2602_p1;
wire   [10:0] zext_ln102_fu_2594_p1;
wire   [10:0] zext_ln103_1_fu_2630_p1;
wire   [10:0] zext_ln103_fu_2622_p1;
wire   [10:0] zext_ln104_1_fu_2658_p1;
wire   [10:0] zext_ln104_fu_2650_p1;
wire   [10:0] zext_ln105_1_fu_2686_p1;
wire   [10:0] zext_ln105_fu_2678_p1;
wire   [10:0] zext_ln106_1_fu_2714_p1;
wire   [10:0] zext_ln106_fu_2706_p1;
wire   [10:0] zext_ln108_1_fu_2752_p1;
wire   [10:0] zext_ln108_fu_2744_p1;
wire   [10:0] zext_ln109_1_fu_2780_p1;
wire   [10:0] zext_ln109_fu_2772_p1;
wire   [10:0] zext_ln110_1_fu_2808_p1;
wire   [10:0] zext_ln110_fu_2800_p1;
wire   [10:0] zext_ln111_1_fu_2836_p1;
wire   [10:0] zext_ln111_fu_2828_p1;
wire   [10:0] zext_ln113_1_fu_2874_p1;
wire   [10:0] zext_ln113_fu_2866_p1;
wire   [10:0] zext_ln114_1_fu_2902_p1;
wire   [10:0] zext_ln114_fu_2894_p1;
wire   [10:0] zext_ln115_1_fu_2930_p1;
wire   [10:0] zext_ln115_fu_2922_p1;
wire   [10:0] zext_ln117_1_fu_2968_p1;
wire   [10:0] zext_ln117_fu_2960_p1;
wire   [10:0] zext_ln118_1_fu_2996_p1;
wire   [10:0] zext_ln118_fu_2988_p1;
wire   [10:0] zext_ln120_1_fu_3034_p1;
wire   [10:0] zext_ln120_fu_3026_p1;
wire   [9:0] zext_ln130_fu_3126_p1;
wire   [9:0] zext_ln130_1_fu_3134_p1;
wire   [9:0] zext_ln131_fu_3154_p1;
wire   [9:0] zext_ln131_1_fu_3162_p1;
wire   [9:0] zext_ln132_fu_3182_p1;
wire   [9:0] zext_ln132_1_fu_3190_p1;
wire   [9:0] zext_ln128_fu_3232_p1;
wire   [9:0] zext_ln128_1_fu_3240_p1;
wire   [9:0] zext_ln129_fu_3260_p1;
wire   [9:0] zext_ln129_1_fu_3268_p1;
wire   [9:0] zext_ln130_2_fu_3288_p1;
wire   [9:0] zext_ln130_9_fu_3296_p1;
wire   [9:0] zext_ln131_2_fu_3316_p1;
wire   [9:0] zext_ln131_9_fu_3324_p1;
wire   [9:0] zext_ln132_2_fu_3344_p1;
wire   [9:0] zext_ln132_9_fu_3352_p1;
wire   [9:0] zext_ln127_fu_3390_p1;
wire   [9:0] zext_ln127_1_fu_3398_p1;
wire   [9:0] zext_ln128_2_fu_3418_p1;
wire   [9:0] zext_ln128_3_fu_3426_p1;
wire   [9:0] zext_ln129_2_fu_3446_p1;
wire   [9:0] zext_ln129_3_fu_3454_p1;
wire   [9:0] zext_ln130_3_fu_3474_p1;
wire   [9:0] zext_ln130_10_fu_3482_p1;
wire   [9:0] zext_ln131_3_fu_3502_p1;
wire   [9:0] zext_ln131_10_fu_3510_p1;
wire   [9:0] zext_ln132_3_fu_3530_p1;
wire   [9:0] zext_ln132_10_fu_3538_p1;
wire   [9:0] zext_ln127_2_fu_3576_p1;
wire   [9:0] zext_ln127_3_fu_3584_p1;
wire   [9:0] zext_ln128_4_fu_3604_p1;
wire   [9:0] zext_ln128_9_fu_3612_p1;
wire   [9:0] zext_ln129_4_fu_3632_p1;
wire   [9:0] zext_ln129_9_fu_3640_p1;
wire   [9:0] zext_ln130_4_fu_3660_p1;
wire   [9:0] zext_ln130_11_fu_3668_p1;
wire   [9:0] zext_ln131_4_fu_3688_p1;
wire   [9:0] zext_ln131_11_fu_3696_p1;
wire   [9:0] zext_ln132_4_fu_3716_p1;
wire   [9:0] zext_ln132_11_fu_3724_p1;
wire   [9:0] zext_ln126_fu_3758_p1;
wire   [9:0] zext_ln126_1_fu_3766_p1;
wire   [9:0] zext_ln127_4_fu_3786_p1;
wire   [9:0] zext_ln127_5_fu_3794_p1;
wire   [9:0] zext_ln128_5_fu_3814_p1;
wire   [9:0] zext_ln128_10_fu_3822_p1;
wire   [9:0] zext_ln129_5_fu_3842_p1;
wire   [9:0] zext_ln129_10_fu_3850_p1;
wire   [9:0] zext_ln130_5_fu_3870_p1;
wire   [9:0] zext_ln130_12_fu_3878_p1;
wire   [9:0] zext_ln131_5_fu_3898_p1;
wire   [9:0] zext_ln131_12_fu_3906_p1;
wire   [9:0] zext_ln132_5_fu_3926_p1;
wire   [9:0] zext_ln132_12_fu_3934_p1;
wire   [9:0] zext_ln126_2_fu_3968_p1;
wire   [9:0] zext_ln126_3_fu_3976_p1;
wire   [9:0] zext_ln127_6_fu_3996_p1;
wire   [9:0] zext_ln127_9_fu_4004_p1;
wire   [9:0] zext_ln128_6_fu_4024_p1;
wire   [9:0] zext_ln128_11_fu_4032_p1;
wire   [9:0] zext_ln129_6_fu_4052_p1;
wire   [9:0] zext_ln129_11_fu_4060_p1;
wire   [9:0] zext_ln130_6_fu_4080_p1;
wire   [9:0] zext_ln130_13_fu_4088_p1;
wire   [9:0] zext_ln131_6_fu_4108_p1;
wire   [9:0] zext_ln131_13_fu_4116_p1;
wire   [9:0] zext_ln132_6_fu_4136_p1;
wire   [9:0] zext_ln132_13_fu_4144_p1;
wire   [9:0] zext_ln126_4_fu_4178_p1;
wire   [9:0] zext_ln126_5_fu_4186_p1;
wire   [9:0] zext_ln127_7_fu_4206_p1;
wire   [9:0] zext_ln127_10_fu_4214_p1;
wire   [9:0] zext_ln128_7_fu_4234_p1;
wire   [9:0] zext_ln128_12_fu_4242_p1;
wire   [9:0] zext_ln129_7_fu_4262_p1;
wire   [9:0] zext_ln129_12_fu_4270_p1;
wire   [9:0] zext_ln130_7_fu_4290_p1;
wire   [9:0] zext_ln130_14_fu_4298_p1;
wire   [9:0] zext_ln131_7_fu_4318_p1;
wire   [9:0] zext_ln131_14_fu_4326_p1;
wire   [9:0] zext_ln132_7_fu_4346_p1;
wire   [9:0] zext_ln132_14_fu_4354_p1;
wire   [9:0] zext_ln125_fu_4384_p1;
wire   [9:0] zext_ln125_1_fu_4392_p1;
wire   [9:0] zext_ln126_6_fu_4412_p1;
wire   [9:0] zext_ln126_7_fu_4420_p1;
wire   [9:0] zext_ln127_8_fu_4440_p1;
wire   [9:0] zext_ln127_11_fu_4448_p1;
wire   [9:0] zext_ln128_8_fu_4472_p1;
wire   [9:0] zext_ln128_13_fu_4480_p1;
wire   [9:0] zext_ln129_8_fu_4500_p1;
wire   [9:0] zext_ln129_13_fu_4508_p1;
wire   [9:0] zext_ln130_8_fu_4528_p1;
wire   [9:0] zext_ln130_15_fu_4536_p1;
wire   [9:0] zext_ln131_8_fu_4556_p1;
wire   [9:0] zext_ln131_15_fu_4564_p1;
wire   [9:0] zext_ln132_8_fu_4584_p1;
wire   [9:0] zext_ln132_15_fu_4592_p1;
wire   [8:0] zext_ln144_1_fu_5348_p1;
wire   [8:0] zext_ln144_fu_5344_p1;
wire   [8:0] zext_ln145_1_fu_5368_p1;
wire   [8:0] zext_ln145_fu_5364_p1;
wire   [8:0] zext_ln146_1_fu_5388_p1;
wire   [8:0] zext_ln146_fu_5384_p1;
wire   [8:0] zext_ln147_1_fu_5408_p1;
wire   [8:0] zext_ln147_fu_5404_p1;
wire   [8:0] zext_ln148_1_fu_5428_p1;
wire   [8:0] zext_ln148_fu_5424_p1;
wire   [8:0] zext_ln149_1_fu_5448_p1;
wire   [8:0] zext_ln149_fu_5444_p1;
wire   [8:0] zext_ln150_1_fu_5468_p1;
wire   [8:0] zext_ln150_fu_5464_p1;
wire   [8:0] zext_ln151_1_fu_5488_p1;
wire   [8:0] zext_ln151_fu_5484_p1;
wire  signed [7:0] mul_ln86_fu_5510_p0;
wire   [10:0] mul_ln86_fu_5510_p1;
wire  signed [7:0] mul_ln86_1_fu_5517_p0;
wire   [10:0] mul_ln86_1_fu_5517_p1;
wire  signed [7:0] mul_ln86_2_fu_5524_p0;
wire   [10:0] mul_ln86_2_fu_5524_p1;
wire  signed [7:0] mul_ln86_3_fu_5531_p0;
wire   [10:0] mul_ln86_3_fu_5531_p1;
wire  signed [7:0] mul_ln86_4_fu_5538_p0;
wire   [10:0] mul_ln86_4_fu_5538_p1;
wire  signed [7:0] mul_ln86_5_fu_5545_p0;
wire   [10:0] mul_ln86_5_fu_5545_p1;
wire  signed [6:0] mul_ln86_6_fu_5552_p0;
wire   [10:0] mul_ln86_6_fu_5552_p1;
wire  signed [5:0] mul_ln86_7_fu_5559_p0;
wire   [10:0] mul_ln86_7_fu_5559_p1;
wire  signed [5:0] mul_ln86_8_fu_5566_p0;
wire   [10:0] mul_ln86_8_fu_5566_p1;
wire  signed [7:0] mul_ln86_9_fu_5573_p0;
wire   [9:0] mul_ln86_9_fu_5573_p1;
wire  signed [6:0] mul_ln86_10_fu_5580_p0;
wire   [10:0] mul_ln86_10_fu_5580_p1;
wire   [6:0] mul_ln86_11_fu_5587_p0;
wire   [10:0] mul_ln86_11_fu_5587_p1;
wire   [6:0] mul_ln86_12_fu_5594_p0;
wire   [10:0] mul_ln86_12_fu_5594_p1;
wire   [6:0] mul_ln86_13_fu_5601_p0;
wire   [10:0] mul_ln86_13_fu_5601_p1;
wire   [6:0] mul_ln86_14_fu_5608_p0;
wire   [9:0] mul_ln86_14_fu_5608_p1;
wire   [7:0] mul_ln86_15_fu_5615_p0;
wire   [10:0] mul_ln86_15_fu_5615_p1;
wire   [7:0] mul_ln86_16_fu_5622_p0;
wire   [10:0] mul_ln86_16_fu_5622_p1;
wire   [7:0] mul_ln86_17_fu_5629_p0;
wire   [9:0] mul_ln86_17_fu_5629_p1;
wire   [7:0] mul_ln86_18_fu_5636_p0;
wire   [10:0] mul_ln86_18_fu_5636_p1;
wire   [7:0] mul_ln86_19_fu_5643_p0;
wire   [10:0] mul_ln86_19_fu_5643_p1;
wire   [7:0] mul_ln86_20_fu_5650_p0;
wire   [9:0] mul_ln86_20_fu_5650_p1;
wire   [7:0] mul_ln86_21_fu_5657_p0;
wire   [10:0] mul_ln86_21_fu_5657_p1;
reg   [0:0] ap_NS_fsm;
wire   [17:0] mul_ln86_10_fu_5580_p10;
wire   [17:0] mul_ln86_11_fu_5587_p10;
wire   [17:0] mul_ln86_12_fu_5594_p10;
wire   [17:0] mul_ln86_13_fu_5601_p10;
wire   [16:0] mul_ln86_14_fu_5608_p10;
wire   [18:0] mul_ln86_15_fu_5615_p10;
wire   [18:0] mul_ln86_16_fu_5622_p10;
wire   [17:0] mul_ln86_17_fu_5629_p10;
wire   [18:0] mul_ln86_18_fu_5636_p10;
wire   [18:0] mul_ln86_19_fu_5643_p10;
wire   [18:0] mul_ln86_1_fu_5517_p10;
wire   [17:0] mul_ln86_20_fu_5650_p10;
wire   [18:0] mul_ln86_21_fu_5657_p10;
wire   [18:0] mul_ln86_2_fu_5524_p10;
wire   [18:0] mul_ln86_3_fu_5531_p10;
wire   [18:0] mul_ln86_4_fu_5538_p10;
wire   [18:0] mul_ln86_5_fu_5545_p10;
wire   [17:0] mul_ln86_6_fu_5552_p10;
wire   [16:0] mul_ln86_7_fu_5559_p10;
wire   [16:0] mul_ln86_8_fu_5566_p10;
wire   [17:0] mul_ln86_9_fu_5573_p10;
wire   [18:0] mul_ln86_fu_5510_p10;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 sum_l3_0 = 23'd0;
#0 sum_l3_1 = 23'd0;
#0 sum_l2_0_0 = 22'd0;
#0 sum_l2_0_1 = 22'd0;
#0 sum_l2_1_0 = 22'd0;
#0 sum_l2_1_1 = 22'd0;
#0 sum_l1_0_0 = 21'd0;
#0 sum_l1_0_1 = 21'd0;
#0 sum_l1_0_2 = 21'd0;
#0 sum_l1_0_3 = 20'd0;
#0 sum_l1_1_0 = 20'd0;
#0 sum_l1_1_1 = 21'd0;
#0 sum_l1_1_2 = 20'd0;
#0 sum_l1_1_3 = 21'd0;
#0 sum_l0_0_0 = 20'd0;
#0 sum_l0_1_0 = 19'd0;
#0 sum_l0_0_1 = 20'd0;
#0 sum_l0_1_1 = 18'd0;
#0 sum_l0_0_2 = 20'd0;
#0 sum_l0_1_2 = 17'd0;
#0 sum_l0_0_3 = 19'd0;
#0 sum_l0_1_3 = 18'd0;
#0 sum_l0_2_0 = 18'd0;
#0 sum_l0_3_0 = 19'd0;
#0 sum_l0_2_1 = 18'd0;
#0 sum_l0_3_1 = 19'd0;
#0 sum_l0_2_2 = 17'd0;
#0 sum_l0_3_2 = 19'd0;
#0 sum_l0_2_3 = 18'd0;
#0 sum_l0_3_3 = 20'd0;
#0 prod_0_0 = 19'd0;
#0 prod_1_0 = 18'd0;
#0 prod_0_1 = 19'd0;
#0 prod_1_1 = 19'd0;
#0 prod_0_2 = 19'd0;
#0 prod_1_2 = 19'd0;
#0 prod_0_3 = 19'd0;
#0 prod_1_3 = 18'd0;
#0 prod_2_0 = 18'd0;
#0 prod_3_0 = 18'd0;
#0 prod_2_1 = 17'd0;
#0 prod_3_1 = 16'd0;
#0 prod_2_2 = 17'd0;
#0 prod_3_2 = 14'd0;
#0 prod_2_3 = 18'd0;
#0 prod_3_3 = 16'd0;
#0 prod_4_0 = 16'd0;
#0 prod_5_0 = 18'd0;
#0 prod_4_1 = 14'd0;
#0 prod_5_1 = 18'd0;
#0 prod_4_2 = 16'd0;
#0 prod_5_2 = 17'd0;
#0 prod_4_3 = 18'd0;
#0 prod_5_3 = 19'd0;
#0 prod_6_0 = 18'd0;
#0 prod_7_0 = 19'd0;
#0 prod_6_1 = 19'd0;
#0 prod_7_1 = 18'd0;
#0 prod_6_2 = 18'd0;
#0 prod_7_2 = 19'd0;
#0 prod_6_3 = 19'd0;
#0 prod_7_3 = 18'd0;
#0 reg2_0_0 = 11'd0;
#0 reg2_0_1 = 11'd0;
#0 reg2_0_2 = 11'd0;
#0 reg2_0_3 = 11'd0;
#0 reg2_1_0 = 11'd0;
#0 reg2_1_1 = 11'd0;
#0 reg2_1_2 = 11'd0;
#0 reg2_1_3 = 11'd0;
#0 reg2_2_0 = 11'd0;
#0 reg2_2_1 = 11'd0;
#0 reg2_2_2 = 11'd0;
#0 reg2_2_3 = 10'd0;
#0 reg2_3_0 = 11'd0;
#0 reg2_3_1 = 11'd0;
#0 reg2_3_2 = 11'd0;
#0 reg2_3_3 = 11'd0;
#0 reg2_4_0 = 11'd0;
#0 reg2_4_1 = 10'd0;
#0 reg2_4_2 = 11'd0;
#0 reg2_4_3 = 11'd0;
#0 reg2_5_0 = 11'd0;
#0 reg2_5_1 = 11'd0;
#0 reg2_5_2 = 10'd0;
#0 reg2_5_3 = 11'd0;
#0 reg2_6_0 = 11'd0;
#0 reg2_6_1 = 11'd0;
#0 reg2_6_2 = 10'd0;
#0 reg2_6_3 = 11'd0;
#0 reg2_7_0 = 11'd0;
#0 reg2_7_1 = 10'd0;
#0 reg2_7_2 = 11'd0;
#0 reg2_7_3 = 9'd0;
#0 reg1_0_8 = 9'd0;
#0 reg1_8_0 = 10'd0;
#0 reg1_1_5 = 10'd0;
#0 reg1_5_1 = 10'd0;
#0 reg1_1_6 = 10'd0;
#0 reg1_6_1 = 10'd0;
#0 reg1_1_7 = 10'd0;
#0 reg1_7_1 = 10'd0;
#0 reg1_1_8 = 9'd0;
#0 reg1_8_1 = 10'd0;
#0 reg1_2_3 = 10'd0;
#0 reg1_3_2 = 10'd0;
#0 reg1_2_4 = 10'd0;
#0 reg1_4_2 = 10'd0;
#0 reg1_2_5 = 10'd0;
#0 reg1_5_2 = 10'd0;
#0 reg1_2_6 = 10'd0;
#0 reg1_6_2 = 10'd0;
#0 reg1_2_7 = 10'd0;
#0 reg1_7_2 = 10'd0;
#0 reg1_2_8 = 9'd0;
#0 reg1_8_2 = 10'd0;
#0 reg1_3_3 = 10'd0;
#0 reg1_3_4 = 10'd0;
#0 reg1_4_3 = 10'd0;
#0 reg1_3_5 = 10'd0;
#0 reg1_5_3 = 10'd0;
#0 reg1_3_6 = 10'd0;
#0 reg1_6_3 = 10'd0;
#0 reg1_3_7 = 10'd0;
#0 reg1_7_3 = 10'd0;
#0 reg1_3_8 = 9'd0;
#0 reg1_8_3 = 10'd0;
#0 reg1_4_4 = 10'd0;
#0 reg1_4_5 = 10'd0;
#0 reg1_5_4 = 10'd0;
#0 reg1_4_6 = 10'd0;
#0 reg1_6_4 = 10'd0;
#0 reg1_4_7 = 10'd0;
#0 reg1_7_4 = 10'd0;
#0 reg1_4_8 = 9'd0;
#0 reg1_8_4 = 10'd0;
#0 reg1_5_5 = 10'd0;
#0 reg1_5_6 = 10'd0;
#0 reg1_6_5 = 10'd0;
#0 reg1_5_7 = 10'd0;
#0 reg1_7_5 = 10'd0;
#0 reg1_5_8 = 9'd0;
#0 reg1_8_5 = 10'd0;
#0 reg1_6_6 = 10'd0;
#0 reg1_6_7 = 10'd0;
#0 reg1_7_6 = 10'd0;
#0 reg1_6_8 = 9'd0;
#0 reg1_8_6 = 10'd0;
#0 reg1_7_7 = 10'd0;
#0 reg1_7_8 = 9'd0;
#0 reg1_8_7 = 10'd0;
#0 reg1_8_8 = 9'd0;
#0 reg0_0_0 = 9'd0;
#0 reg0_0_1 = 9'd0;
#0 reg0_0_2 = 9'd0;
#0 reg0_0_3 = 9'd0;
#0 reg0_0_4 = 9'd0;
#0 reg0_0_5 = 9'd0;
#0 reg0_0_6 = 9'd0;
#0 reg0_0_7 = 9'd0;
#0 reg0_0_8 = 9'd0;
#0 reg0_1_0 = 9'd0;
#0 reg0_1_1 = 9'd0;
#0 reg0_1_2 = 9'd0;
#0 reg0_1_3 = 9'd0;
#0 reg0_1_4 = 9'd0;
#0 reg0_1_5 = 9'd0;
#0 reg0_1_11 = 9'd0;
#0 reg0_1_6 = 9'd0;
#0 reg0_1_10 = 9'd0;
#0 reg0_1_7 = 9'd0;
#0 reg0_1_9 = 9'd0;
#0 reg0_1_8 = 9'd0;
#0 reg0_2_0 = 9'd0;
#0 reg0_2_1 = 9'd0;
#0 reg0_2_2 = 9'd0;
#0 reg0_2_3 = 9'd0;
#0 reg0_2_13 = 9'd0;
#0 reg0_2_4 = 9'd0;
#0 reg0_2_12 = 9'd0;
#0 reg0_2_5 = 9'd0;
#0 reg0_2_11 = 9'd0;
#0 reg0_2_6 = 9'd0;
#0 reg0_2_10 = 9'd0;
#0 reg0_2_7 = 9'd0;
#0 reg0_2_9 = 9'd0;
#0 reg0_2_8 = 9'd0;
#0 reg0_3_0 = 9'd0;
#0 reg0_3_1 = 9'd0;
#0 reg0_3_2 = 9'd0;
#0 reg0_3_14 = 9'd0;
#0 reg0_3_3 = 9'd0;
#0 reg0_3_13 = 9'd0;
#0 reg0_3_4 = 9'd0;
#0 reg0_3_12 = 9'd0;
#0 reg0_3_5 = 9'd0;
#0 reg0_3_11 = 9'd0;
#0 reg0_3_6 = 9'd0;
#0 reg0_3_10 = 9'd0;
#0 reg0_3_7 = 9'd0;
#0 reg0_3_9 = 9'd0;
#0 reg0_3_8 = 9'd0;
#0 reg0_4_0 = 9'd0;
#0 reg0_4_1 = 9'd0;
#0 reg0_4_2 = 9'd0;
#0 reg0_4_14 = 9'd0;
#0 reg0_4_3 = 9'd0;
#0 reg0_4_13 = 9'd0;
#0 reg0_4_4 = 9'd0;
#0 reg0_4_12 = 9'd0;
#0 reg0_4_5 = 9'd0;
#0 reg0_4_11 = 9'd0;
#0 reg0_4_6 = 9'd0;
#0 reg0_4_10 = 9'd0;
#0 reg0_4_7 = 9'd0;
#0 reg0_4_9 = 9'd0;
#0 reg0_4_8 = 9'd0;
#0 reg0_5_0 = 9'd0;
#0 reg0_5_1 = 9'd0;
#0 reg0_5_15 = 9'd0;
#0 reg0_5_2 = 9'd0;
#0 reg0_5_14 = 9'd0;
#0 reg0_5_3 = 9'd0;
#0 reg0_5_13 = 9'd0;
#0 reg0_5_4 = 9'd0;
#0 reg0_5_12 = 9'd0;
#0 reg0_5_5 = 9'd0;
#0 reg0_5_11 = 9'd0;
#0 reg0_5_6 = 9'd0;
#0 reg0_5_10 = 9'd0;
#0 reg0_5_7 = 9'd0;
#0 reg0_5_9 = 9'd0;
#0 reg0_5_8 = 9'd0;
#0 reg0_6_0 = 9'd0;
#0 reg0_6_1 = 9'd0;
#0 reg0_6_15 = 9'd0;
#0 reg0_6_2 = 9'd0;
#0 reg0_6_14 = 9'd0;
#0 reg0_6_3 = 9'd0;
#0 reg0_6_13 = 9'd0;
#0 reg0_6_4 = 9'd0;
#0 reg0_6_12 = 9'd0;
#0 reg0_6_5 = 9'd0;
#0 reg0_6_11 = 9'd0;
#0 reg0_6_6 = 9'd0;
#0 reg0_6_10 = 9'd0;
#0 reg0_6_7 = 9'd0;
#0 reg0_6_9 = 9'd0;
#0 reg0_6_8 = 9'd0;
#0 reg0_7_0 = 9'd0;
#0 reg0_7_1 = 9'd0;
#0 reg0_7_15 = 9'd0;
#0 reg0_7_2 = 9'd0;
#0 reg0_7_14 = 9'd0;
#0 reg0_7_3 = 9'd0;
#0 reg0_7_13 = 9'd0;
#0 reg0_7_4 = 9'd0;
#0 reg0_7_12 = 9'd0;
#0 reg0_7_5 = 9'd0;
#0 reg0_7_11 = 9'd0;
#0 reg0_7_6 = 9'd0;
#0 reg0_7_10 = 9'd0;
#0 reg0_7_7 = 9'd0;
#0 reg0_7_9 = 9'd0;
#0 reg0_7_8 = 9'd0;
#0 reg0_8_0 = 8'd0;
#0 reg0_8_16 = 9'd0;
#0 reg0_8_1 = 8'd0;
#0 reg0_8_15 = 9'd0;
#0 reg0_8_2 = 8'd0;
#0 reg0_8_14 = 9'd0;
#0 reg0_8_3 = 8'd0;
#0 reg0_8_13 = 9'd0;
#0 reg0_8_4 = 9'd0;
#0 reg0_8_12 = 9'd0;
#0 reg0_8_5 = 9'd0;
#0 reg0_8_11 = 9'd0;
#0 reg0_8_6 = 9'd0;
#0 reg0_8_10 = 9'd0;
#0 reg0_8_7 = 9'd0;
#0 reg0_8_9 = 9'd0;
#0 reg0_8_8 = 9'd0;
end

filter_accel_mul_bkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 19 ))
filter_accel_mul_bkb_U1(
    .din0(mul_ln86_fu_5510_p0),
    .din1(mul_ln86_fu_5510_p1),
    .dout(mul_ln86_fu_5510_p2)
);

filter_accel_mul_bkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 19 ))
filter_accel_mul_bkb_U2(
    .din0(mul_ln86_1_fu_5517_p0),
    .din1(mul_ln86_1_fu_5517_p1),
    .dout(mul_ln86_1_fu_5517_p2)
);

filter_accel_mul_bkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 19 ))
filter_accel_mul_bkb_U3(
    .din0(mul_ln86_2_fu_5524_p0),
    .din1(mul_ln86_2_fu_5524_p1),
    .dout(mul_ln86_2_fu_5524_p2)
);

filter_accel_mul_bkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 19 ))
filter_accel_mul_bkb_U4(
    .din0(mul_ln86_3_fu_5531_p0),
    .din1(mul_ln86_3_fu_5531_p1),
    .dout(mul_ln86_3_fu_5531_p2)
);

filter_accel_mul_bkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 19 ))
filter_accel_mul_bkb_U5(
    .din0(mul_ln86_4_fu_5538_p0),
    .din1(mul_ln86_4_fu_5538_p1),
    .dout(mul_ln86_4_fu_5538_p2)
);

filter_accel_mul_bkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 19 ))
filter_accel_mul_bkb_U6(
    .din0(mul_ln86_5_fu_5545_p0),
    .din1(mul_ln86_5_fu_5545_p1),
    .dout(mul_ln86_5_fu_5545_p2)
);

filter_accel_mul_cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 18 ))
filter_accel_mul_cud_U7(
    .din0(mul_ln86_6_fu_5552_p0),
    .din1(mul_ln86_6_fu_5552_p1),
    .dout(mul_ln86_6_fu_5552_p2)
);

filter_accel_mul_dEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 17 ))
filter_accel_mul_dEe_U8(
    .din0(mul_ln86_7_fu_5559_p0),
    .din1(mul_ln86_7_fu_5559_p1),
    .dout(mul_ln86_7_fu_5559_p2)
);

filter_accel_mul_dEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 17 ))
filter_accel_mul_dEe_U9(
    .din0(mul_ln86_8_fu_5566_p0),
    .din1(mul_ln86_8_fu_5566_p1),
    .dout(mul_ln86_8_fu_5566_p2)
);

filter_accel_mul_eOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 18 ))
filter_accel_mul_eOg_U10(
    .din0(mul_ln86_9_fu_5573_p0),
    .din1(mul_ln86_9_fu_5573_p1),
    .dout(mul_ln86_9_fu_5573_p2)
);

filter_accel_mul_cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 18 ))
filter_accel_mul_cud_U11(
    .din0(mul_ln86_10_fu_5580_p0),
    .din1(mul_ln86_10_fu_5580_p1),
    .dout(mul_ln86_10_fu_5580_p2)
);

filter_accel_mul_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 18 ))
filter_accel_mul_fYi_U12(
    .din0(mul_ln86_11_fu_5587_p0),
    .din1(mul_ln86_11_fu_5587_p1),
    .dout(mul_ln86_11_fu_5587_p2)
);

filter_accel_mul_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 18 ))
filter_accel_mul_fYi_U13(
    .din0(mul_ln86_12_fu_5594_p0),
    .din1(mul_ln86_12_fu_5594_p1),
    .dout(mul_ln86_12_fu_5594_p2)
);

filter_accel_mul_fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 18 ))
filter_accel_mul_fYi_U14(
    .din0(mul_ln86_13_fu_5601_p0),
    .din1(mul_ln86_13_fu_5601_p1),
    .dout(mul_ln86_13_fu_5601_p2)
);

filter_accel_mul_g8j #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 17 ))
filter_accel_mul_g8j_U15(
    .din0(mul_ln86_14_fu_5608_p0),
    .din1(mul_ln86_14_fu_5608_p1),
    .dout(mul_ln86_14_fu_5608_p2)
);

filter_accel_mul_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 19 ))
filter_accel_mul_hbi_U16(
    .din0(mul_ln86_15_fu_5615_p0),
    .din1(mul_ln86_15_fu_5615_p1),
    .dout(mul_ln86_15_fu_5615_p2)
);

filter_accel_mul_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 19 ))
filter_accel_mul_hbi_U17(
    .din0(mul_ln86_16_fu_5622_p0),
    .din1(mul_ln86_16_fu_5622_p1),
    .dout(mul_ln86_16_fu_5622_p2)
);

filter_accel_mul_ibs #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 18 ))
filter_accel_mul_ibs_U18(
    .din0(mul_ln86_17_fu_5629_p0),
    .din1(mul_ln86_17_fu_5629_p1),
    .dout(mul_ln86_17_fu_5629_p2)
);

filter_accel_mul_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 19 ))
filter_accel_mul_hbi_U19(
    .din0(mul_ln86_18_fu_5636_p0),
    .din1(mul_ln86_18_fu_5636_p1),
    .dout(mul_ln86_18_fu_5636_p2)
);

filter_accel_mul_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 19 ))
filter_accel_mul_hbi_U20(
    .din0(mul_ln86_19_fu_5643_p0),
    .din1(mul_ln86_19_fu_5643_p1),
    .dout(mul_ln86_19_fu_5643_p2)
);

filter_accel_mul_ibs #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 18 ))
filter_accel_mul_ibs_U21(
    .din0(mul_ln86_20_fu_5650_p0),
    .din1(mul_ln86_20_fu_5650_p1),
    .dout(mul_ln86_20_fu_5650_p2)
);

filter_accel_mul_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 19 ))
filter_accel_mul_hbi_U22(
    .din0(mul_ln86_21_fu_5657_p0),
    .din1(mul_ln86_21_fu_5657_p1),
    .dout(mul_ln86_21_fu_5657_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        prod_0_0 <= mul_ln86_fu_5510_p2;
        prod_0_1 <= mul_ln86_1_fu_5517_p2;
        prod_0_2 <= mul_ln86_2_fu_5524_p2;
        prod_0_3 <= mul_ln86_3_fu_5531_p2;
        prod_1_0[17 : 6] <= sub_ln86_fu_1692_p2[17 : 6];
        prod_1_1 <= mul_ln86_4_fu_5538_p2;
        prod_1_2 <= mul_ln86_5_fu_5545_p2;
        prod_1_3 <= mul_ln86_6_fu_5552_p2;
        prod_2_0[17 : 2] <= sub_ln86_2_fu_1781_p2[17 : 2];
        prod_2_1 <= mul_ln86_7_fu_5559_p2;
        prod_2_2 <= mul_ln86_8_fu_5566_p2;
        prod_2_3 <= mul_ln86_9_fu_5573_p2;
        prod_3_0 <= mul_ln86_10_fu_5580_p2;
        prod_3_1 <= sub_ln86_7_fu_1865_p2;
        prod_3_2 <= sub_ln86_3_fu_1897_p2;
        prod_3_3[15 : 1] <= sub_ln86_4_fu_1937_p2[15 : 1];
        prod_4_0[15 : 1] <= add_ln86_fu_1977_p2[15 : 1];
        prod_4_1[13 : 3] <= sub_ln86_5_fu_2005_p2[13 : 3];
        prod_4_2[15 : 1] <= add_ln86_1_fu_2045_p2[15 : 1];
        prod_4_3 <= mul_ln86_11_fu_5587_p2;
        prod_5_0 <= mul_ln86_12_fu_5594_p2;
        prod_5_1 <= mul_ln86_13_fu_5601_p2;
        prod_5_2 <= mul_ln86_14_fu_5608_p2;
        prod_5_3 <= mul_ln86_15_fu_5615_p2;
        prod_6_0[17 : 4] <= add_ln86_2_fu_2150_p2[17 : 4];
        prod_6_1 <= mul_ln86_16_fu_5622_p2;
        prod_6_2 <= mul_ln86_17_fu_5629_p2;
        prod_6_3 <= mul_ln86_18_fu_5636_p2;
        prod_7_0 <= mul_ln86_19_fu_5643_p2;
        prod_7_1 <= mul_ln86_20_fu_5650_p2;
        prod_7_2 <= mul_ln86_21_fu_5657_p2;
        prod_7_3 <= sub_ln86_6_fu_2260_p2;
        reg0_0_0 <= add_ln144_fu_5352_p2;
        reg0_0_1 <= reg0_0_0;
        reg0_0_2 <= reg0_0_1;
        reg0_0_3 <= reg0_0_2;
        reg0_0_4 <= reg0_0_3;
        reg0_0_5 <= reg0_0_4;
        reg0_0_6 <= reg0_0_5;
        reg0_0_7 <= reg0_0_6;
        reg0_0_8 <= reg0_0_7;
        reg0_1_0 <= add_ln145_fu_5372_p2;
        reg0_1_1 <= reg0_1_0;
        reg0_1_10 <= reg0_1_9;
        reg0_1_11 <= reg0_1_10;
        reg0_1_2 <= reg0_1_1;
        reg0_1_3 <= reg0_1_2;
        reg0_1_4 <= reg0_1_3;
        reg0_1_5 <= reg0_1_4;
        reg0_1_6 <= reg0_1_5;
        reg0_1_7 <= reg0_1_6;
        reg0_1_8 <= reg0_1_7;
        reg0_1_9 <= reg0_1_8;
        reg0_2_0 <= add_ln146_fu_5392_p2;
        reg0_2_1 <= reg0_2_0;
        reg0_2_10 <= reg0_2_9;
        reg0_2_11 <= reg0_2_10;
        reg0_2_12 <= reg0_2_11;
        reg0_2_13 <= reg0_2_12;
        reg0_2_2 <= reg0_2_1;
        reg0_2_3 <= reg0_2_2;
        reg0_2_4 <= reg0_2_3;
        reg0_2_5 <= reg0_2_4;
        reg0_2_6 <= reg0_2_5;
        reg0_2_7 <= reg0_2_6;
        reg0_2_8 <= reg0_2_7;
        reg0_2_9 <= reg0_2_8;
        reg0_3_0 <= add_ln147_fu_5412_p2;
        reg0_3_1 <= reg0_3_0;
        reg0_3_10 <= reg0_3_9;
        reg0_3_11 <= reg0_3_10;
        reg0_3_12 <= reg0_3_11;
        reg0_3_13 <= reg0_3_12;
        reg0_3_14 <= reg0_3_13;
        reg0_3_2 <= reg0_3_1;
        reg0_3_3 <= reg0_3_2;
        reg0_3_4 <= reg0_3_3;
        reg0_3_5 <= reg0_3_4;
        reg0_3_6 <= reg0_3_5;
        reg0_3_7 <= reg0_3_6;
        reg0_3_8 <= reg0_3_7;
        reg0_3_9 <= reg0_3_8;
        reg0_4_0 <= add_ln148_fu_5432_p2;
        reg0_4_1 <= reg0_4_0;
        reg0_4_10 <= reg0_4_9;
        reg0_4_11 <= reg0_4_10;
        reg0_4_12 <= reg0_4_11;
        reg0_4_13 <= reg0_4_12;
        reg0_4_14 <= reg0_4_13;
        reg0_4_2 <= reg0_4_1;
        reg0_4_3 <= reg0_4_2;
        reg0_4_4 <= reg0_4_3;
        reg0_4_5 <= reg0_4_4;
        reg0_4_6 <= reg0_4_5;
        reg0_4_7 <= reg0_4_6;
        reg0_4_8 <= reg0_4_7;
        reg0_4_9 <= reg0_4_8;
        reg0_5_0 <= add_ln149_fu_5452_p2;
        reg0_5_1 <= reg0_5_0;
        reg0_5_10 <= reg0_5_9;
        reg0_5_11 <= reg0_5_10;
        reg0_5_12 <= reg0_5_11;
        reg0_5_13 <= reg0_5_12;
        reg0_5_14 <= reg0_5_13;
        reg0_5_15 <= reg0_5_14;
        reg0_5_2 <= reg0_5_1;
        reg0_5_3 <= reg0_5_2;
        reg0_5_4 <= reg0_5_3;
        reg0_5_5 <= reg0_5_4;
        reg0_5_6 <= reg0_5_5;
        reg0_5_7 <= reg0_5_6;
        reg0_5_8 <= reg0_5_7;
        reg0_5_9 <= reg0_5_8;
        reg0_6_0 <= add_ln150_fu_5472_p2;
        reg0_6_1 <= reg0_6_0;
        reg0_6_10 <= reg0_6_9;
        reg0_6_11 <= reg0_6_10;
        reg0_6_12 <= reg0_6_11;
        reg0_6_13 <= reg0_6_12;
        reg0_6_14 <= reg0_6_13;
        reg0_6_15 <= reg0_6_14;
        reg0_6_2 <= reg0_6_1;
        reg0_6_3 <= reg0_6_2;
        reg0_6_4 <= reg0_6_3;
        reg0_6_5 <= reg0_6_4;
        reg0_6_6 <= reg0_6_5;
        reg0_6_7 <= reg0_6_6;
        reg0_6_8 <= reg0_6_7;
        reg0_6_9 <= reg0_6_8;
        reg0_7_0 <= add_ln151_fu_5492_p2;
        reg0_7_1 <= reg0_7_0;
        reg0_7_10 <= reg0_7_9;
        reg0_7_11 <= reg0_7_10;
        reg0_7_12 <= reg0_7_11;
        reg0_7_13 <= reg0_7_12;
        reg0_7_14 <= reg0_7_13;
        reg0_7_15 <= reg0_7_14;
        reg0_7_2 <= reg0_7_1;
        reg0_7_3 <= reg0_7_2;
        reg0_7_4 <= reg0_7_3;
        reg0_7_5 <= reg0_7_4;
        reg0_7_6 <= reg0_7_5;
        reg0_7_7 <= reg0_7_6;
        reg0_7_8 <= reg0_7_7;
        reg0_7_9 <= reg0_7_8;
        reg0_8_0 <= in8;
        reg0_8_1 <= reg0_8_0;
        reg0_8_10[7 : 0] <= reg0_8_9[7 : 0];
        reg0_8_11[7 : 0] <= reg0_8_10[7 : 0];
        reg0_8_12[7 : 0] <= reg0_8_11[7 : 0];
        reg0_8_13[7 : 0] <= reg0_8_12[7 : 0];
        reg0_8_14[7 : 0] <= reg0_8_13[7 : 0];
        reg0_8_15[7 : 0] <= reg0_8_14[7 : 0];
        reg0_8_16[7 : 0] <= reg0_8_15[7 : 0];
        reg0_8_2 <= reg0_8_1;
        reg0_8_3 <= reg0_8_2;
        reg0_8_4[7 : 0] <= zext_ln128_14_fu_4468_p1[7 : 0];
        reg0_8_5[7 : 0] <= reg0_8_4[7 : 0];
        reg0_8_6[7 : 0] <= reg0_8_5[7 : 0];
        reg0_8_7[7 : 0] <= reg0_8_6[7 : 0];
        reg0_8_8[7 : 0] <= reg0_8_7[7 : 0];
        reg0_8_9[7 : 0] <= reg0_8_8[7 : 0];
        reg1_0_8 <= reg0_0_8;
        reg1_1_5 <= add_ln130_fu_3138_p2;
        reg1_1_6 <= add_ln131_fu_3166_p2;
        reg1_1_7 <= add_ln132_fu_3194_p2;
        reg1_1_8 <= reg0_1_8;
        reg1_2_3 <= add_ln128_fu_3244_p2;
        reg1_2_4 <= add_ln129_fu_3272_p2;
        reg1_2_5 <= add_ln130_1_fu_3300_p2;
        reg1_2_6 <= add_ln131_1_fu_3328_p2;
        reg1_2_7 <= add_ln132_1_fu_3356_p2;
        reg1_2_8 <= reg0_2_8;
        reg1_3_2 <= add_ln127_fu_3402_p2;
        reg1_3_3 <= add_ln128_1_fu_3430_p2;
        reg1_3_4 <= add_ln129_1_fu_3458_p2;
        reg1_3_5 <= add_ln130_2_fu_3486_p2;
        reg1_3_6 <= add_ln131_2_fu_3514_p2;
        reg1_3_7 <= add_ln132_2_fu_3542_p2;
        reg1_3_8 <= reg0_3_8;
        reg1_4_2 <= add_ln127_1_fu_3588_p2;
        reg1_4_3 <= add_ln128_2_fu_3616_p2;
        reg1_4_4 <= add_ln129_2_fu_3644_p2;
        reg1_4_5 <= add_ln130_3_fu_3672_p2;
        reg1_4_6 <= add_ln131_3_fu_3700_p2;
        reg1_4_7 <= add_ln132_3_fu_3728_p2;
        reg1_4_8 <= reg0_4_8;
        reg1_5_1 <= add_ln126_fu_3770_p2;
        reg1_5_2 <= add_ln127_2_fu_3798_p2;
        reg1_5_3 <= add_ln128_3_fu_3826_p2;
        reg1_5_4 <= add_ln129_3_fu_3854_p2;
        reg1_5_5 <= add_ln130_4_fu_3882_p2;
        reg1_5_6 <= add_ln131_4_fu_3910_p2;
        reg1_5_7 <= add_ln132_4_fu_3938_p2;
        reg1_5_8 <= reg0_5_8;
        reg1_6_1 <= add_ln126_1_fu_3980_p2;
        reg1_6_2 <= add_ln127_3_fu_4008_p2;
        reg1_6_3 <= add_ln128_4_fu_4036_p2;
        reg1_6_4 <= add_ln129_4_fu_4064_p2;
        reg1_6_5 <= add_ln130_5_fu_4092_p2;
        reg1_6_6 <= add_ln131_5_fu_4120_p2;
        reg1_6_7 <= add_ln132_5_fu_4148_p2;
        reg1_6_8 <= reg0_6_8;
        reg1_7_1 <= add_ln126_2_fu_4190_p2;
        reg1_7_2 <= add_ln127_4_fu_4218_p2;
        reg1_7_3 <= add_ln128_5_fu_4246_p2;
        reg1_7_4 <= add_ln129_5_fu_4274_p2;
        reg1_7_5 <= add_ln130_6_fu_4302_p2;
        reg1_7_6 <= add_ln131_6_fu_4330_p2;
        reg1_7_7 <= add_ln132_6_fu_4358_p2;
        reg1_7_8 <= reg0_7_8;
        reg1_8_0 <= add_ln125_fu_4396_p2;
        reg1_8_1 <= add_ln126_3_fu_4424_p2;
        reg1_8_2 <= add_ln127_5_fu_4452_p2;
        reg1_8_3 <= add_ln128_6_fu_4484_p2;
        reg1_8_4 <= add_ln129_6_fu_4512_p2;
        reg1_8_5 <= add_ln130_7_fu_4540_p2;
        reg1_8_6 <= add_ln131_7_fu_4568_p2;
        reg1_8_7 <= add_ln132_7_fu_4596_p2;
        reg1_8_8[7 : 0] <= reg0_8_8[7 : 0];
        reg2_0_0 <= add_ln90_fu_2288_p2;
        reg2_0_1 <= add_ln91_fu_2316_p2;
        reg2_0_2 <= add_ln92_fu_2344_p2;
        reg2_0_3 <= add_ln93_fu_2372_p2;
        reg2_1_0 <= add_ln94_fu_2400_p2;
        reg2_1_1 <= add_ln95_fu_2428_p2;
        reg2_1_2 <= add_ln96_fu_2456_p2;
        reg2_1_3 <= add_ln97_fu_2484_p2;
        reg2_2_0 <= add_ln98_fu_2512_p2;
        reg2_2_1 <= add_ln99_fu_2540_p2;
        reg2_2_2 <= add_ln100_fu_2568_p2;
        reg2_2_3 <= reg1_3_3;
        reg2_3_0 <= add_ln102_fu_2606_p2;
        reg2_3_1 <= add_ln103_fu_2634_p2;
        reg2_3_2 <= add_ln104_fu_2662_p2;
        reg2_3_3 <= add_ln105_fu_2690_p2;
        reg2_4_0 <= add_ln106_fu_2718_p2;
        reg2_4_1 <= reg1_4_4;
        reg2_4_2 <= add_ln108_fu_2756_p2;
        reg2_4_3 <= add_ln109_fu_2784_p2;
        reg2_5_0 <= add_ln110_fu_2812_p2;
        reg2_5_1 <= add_ln111_fu_2840_p2;
        reg2_5_2 <= reg1_5_5;
        reg2_5_3 <= add_ln113_fu_2878_p2;
        reg2_6_0 <= add_ln114_fu_2906_p2;
        reg2_6_1 <= add_ln115_fu_2934_p2;
        reg2_6_2 <= reg1_6_6;
        reg2_6_3 <= add_ln117_fu_2972_p2;
        reg2_7_0 <= add_ln118_fu_3000_p2;
        reg2_7_1 <= reg1_7_7;
        reg2_7_2 <= add_ln120_fu_3038_p2;
        reg2_7_3[7 : 0] <= reg1_8_8[7 : 0];
        sum_l0_0_0 <= add_ln78_fu_1232_p2;
        sum_l0_0_1 <= add_ln78_1_fu_1260_p2;
        sum_l0_0_2 <= add_ln78_2_fu_1288_p2;
        sum_l0_0_3 <= add_ln78_3_fu_1312_p2;
        sum_l0_1_0 <= add_ln78_4_fu_1340_p2;
        sum_l0_1_1 <= add_ln78_5_fu_1368_p2;
        sum_l0_1_2 <= add_ln78_6_fu_1392_p2;
        sum_l0_1_3 <= add_ln78_7_fu_1416_p2;
        sum_l0_2_0 <= add_ln78_8_fu_1440_p2;
        sum_l0_2_1 <= add_ln78_9_fu_1464_p2;
        sum_l0_2_2 <= add_ln78_10_fu_1488_p2;
        sum_l0_2_3 <= add_ln78_11_fu_1512_p2;
        sum_l0_3_0 <= add_ln78_12_fu_1536_p2;
        sum_l0_3_1 <= add_ln78_13_fu_1560_p2;
        sum_l0_3_2 <= add_ln78_14_fu_1584_p2;
        sum_l0_3_3 <= add_ln78_15_fu_1612_p2;
        sum_l1_0_0 <= add_ln69_fu_1008_p2;
        sum_l1_0_1 <= add_ln69_1_fu_1036_p2;
        sum_l1_0_2 <= add_ln69_2_fu_1064_p2;
        sum_l1_0_3 <= add_ln69_3_fu_1092_p2;
        sum_l1_1_0 <= add_ln69_4_fu_1120_p2;
        sum_l1_1_1 <= add_ln69_5_fu_1148_p2;
        sum_l1_1_2 <= add_ln69_6_fu_1176_p2;
        sum_l1_1_3 <= add_ln69_7_fu_1204_p2;
        sum_l2_0_0 <= add_ln60_fu_896_p2;
        sum_l2_0_1 <= add_ln60_1_fu_924_p2;
        sum_l2_1_0 <= add_ln60_2_fu_952_p2;
        sum_l2_1_1 <= add_ln60_3_fu_980_p2;
        sum_l3_0 <= add_ln52_fu_840_p2;
        sum_l3_1 <= add_ln52_1_fu_868_p2;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        out_r_ap_vld = 1'b1;
    end else begin
        out_r_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln100_fu_2568_p2 = (zext_ln100_1_fu_2564_p1 + zext_ln100_fu_2556_p1);

assign add_ln102_fu_2606_p2 = (zext_ln102_1_fu_2602_p1 + zext_ln102_fu_2594_p1);

assign add_ln103_fu_2634_p2 = (zext_ln103_1_fu_2630_p1 + zext_ln103_fu_2622_p1);

assign add_ln104_fu_2662_p2 = (zext_ln104_1_fu_2658_p1 + zext_ln104_fu_2650_p1);

assign add_ln105_fu_2690_p2 = (zext_ln105_1_fu_2686_p1 + zext_ln105_fu_2678_p1);

assign add_ln106_fu_2718_p2 = (zext_ln106_1_fu_2714_p1 + zext_ln106_fu_2706_p1);

assign add_ln108_fu_2756_p2 = (zext_ln108_1_fu_2752_p1 + zext_ln108_fu_2744_p1);

assign add_ln109_fu_2784_p2 = (zext_ln109_1_fu_2780_p1 + zext_ln109_fu_2772_p1);

assign add_ln110_fu_2812_p2 = (zext_ln110_1_fu_2808_p1 + zext_ln110_fu_2800_p1);

assign add_ln111_fu_2840_p2 = (zext_ln111_1_fu_2836_p1 + zext_ln111_fu_2828_p1);

assign add_ln113_fu_2878_p2 = (zext_ln113_1_fu_2874_p1 + zext_ln113_fu_2866_p1);

assign add_ln114_fu_2906_p2 = (zext_ln114_1_fu_2902_p1 + zext_ln114_fu_2894_p1);

assign add_ln115_fu_2934_p2 = (zext_ln115_1_fu_2930_p1 + zext_ln115_fu_2922_p1);

assign add_ln117_fu_2972_p2 = (zext_ln117_1_fu_2968_p1 + zext_ln117_fu_2960_p1);

assign add_ln118_fu_3000_p2 = (zext_ln118_1_fu_2996_p1 + zext_ln118_fu_2988_p1);

assign add_ln120_fu_3038_p2 = (zext_ln120_1_fu_3034_p1 + zext_ln120_fu_3026_p1);

assign add_ln125_fu_4396_p2 = (zext_ln125_fu_4384_p1 + zext_ln125_1_fu_4392_p1);

assign add_ln126_1_fu_3980_p2 = (zext_ln126_2_fu_3968_p1 + zext_ln126_3_fu_3976_p1);

assign add_ln126_2_fu_4190_p2 = (zext_ln126_4_fu_4178_p1 + zext_ln126_5_fu_4186_p1);

assign add_ln126_3_fu_4424_p2 = (zext_ln126_6_fu_4412_p1 + zext_ln126_7_fu_4420_p1);

assign add_ln126_fu_3770_p2 = (zext_ln126_fu_3758_p1 + zext_ln126_1_fu_3766_p1);

assign add_ln127_1_fu_3588_p2 = (zext_ln127_2_fu_3576_p1 + zext_ln127_3_fu_3584_p1);

assign add_ln127_2_fu_3798_p2 = (zext_ln127_4_fu_3786_p1 + zext_ln127_5_fu_3794_p1);

assign add_ln127_3_fu_4008_p2 = (zext_ln127_6_fu_3996_p1 + zext_ln127_9_fu_4004_p1);

assign add_ln127_4_fu_4218_p2 = (zext_ln127_7_fu_4206_p1 + zext_ln127_10_fu_4214_p1);

assign add_ln127_5_fu_4452_p2 = (zext_ln127_8_fu_4440_p1 + zext_ln127_11_fu_4448_p1);

assign add_ln127_fu_3402_p2 = (zext_ln127_fu_3390_p1 + zext_ln127_1_fu_3398_p1);

assign add_ln128_1_fu_3430_p2 = (zext_ln128_2_fu_3418_p1 + zext_ln128_3_fu_3426_p1);

assign add_ln128_2_fu_3616_p2 = (zext_ln128_4_fu_3604_p1 + zext_ln128_9_fu_3612_p1);

assign add_ln128_3_fu_3826_p2 = (zext_ln128_5_fu_3814_p1 + zext_ln128_10_fu_3822_p1);

assign add_ln128_4_fu_4036_p2 = (zext_ln128_6_fu_4024_p1 + zext_ln128_11_fu_4032_p1);

assign add_ln128_5_fu_4246_p2 = (zext_ln128_7_fu_4234_p1 + zext_ln128_12_fu_4242_p1);

assign add_ln128_6_fu_4484_p2 = (zext_ln128_8_fu_4472_p1 + zext_ln128_13_fu_4480_p1);

assign add_ln128_fu_3244_p2 = (zext_ln128_fu_3232_p1 + zext_ln128_1_fu_3240_p1);

assign add_ln129_1_fu_3458_p2 = (zext_ln129_2_fu_3446_p1 + zext_ln129_3_fu_3454_p1);

assign add_ln129_2_fu_3644_p2 = (zext_ln129_4_fu_3632_p1 + zext_ln129_9_fu_3640_p1);

assign add_ln129_3_fu_3854_p2 = (zext_ln129_5_fu_3842_p1 + zext_ln129_10_fu_3850_p1);

assign add_ln129_4_fu_4064_p2 = (zext_ln129_6_fu_4052_p1 + zext_ln129_11_fu_4060_p1);

assign add_ln129_5_fu_4274_p2 = (zext_ln129_7_fu_4262_p1 + zext_ln129_12_fu_4270_p1);

assign add_ln129_6_fu_4512_p2 = (zext_ln129_8_fu_4500_p1 + zext_ln129_13_fu_4508_p1);

assign add_ln129_fu_3272_p2 = (zext_ln129_fu_3260_p1 + zext_ln129_1_fu_3268_p1);

assign add_ln130_1_fu_3300_p2 = (zext_ln130_2_fu_3288_p1 + zext_ln130_9_fu_3296_p1);

assign add_ln130_2_fu_3486_p2 = (zext_ln130_3_fu_3474_p1 + zext_ln130_10_fu_3482_p1);

assign add_ln130_3_fu_3672_p2 = (zext_ln130_4_fu_3660_p1 + zext_ln130_11_fu_3668_p1);

assign add_ln130_4_fu_3882_p2 = (zext_ln130_5_fu_3870_p1 + zext_ln130_12_fu_3878_p1);

assign add_ln130_5_fu_4092_p2 = (zext_ln130_6_fu_4080_p1 + zext_ln130_13_fu_4088_p1);

assign add_ln130_6_fu_4302_p2 = (zext_ln130_7_fu_4290_p1 + zext_ln130_14_fu_4298_p1);

assign add_ln130_7_fu_4540_p2 = (zext_ln130_8_fu_4528_p1 + zext_ln130_15_fu_4536_p1);

assign add_ln130_fu_3138_p2 = (zext_ln130_fu_3126_p1 + zext_ln130_1_fu_3134_p1);

assign add_ln131_1_fu_3328_p2 = (zext_ln131_2_fu_3316_p1 + zext_ln131_9_fu_3324_p1);

assign add_ln131_2_fu_3514_p2 = (zext_ln131_3_fu_3502_p1 + zext_ln131_10_fu_3510_p1);

assign add_ln131_3_fu_3700_p2 = (zext_ln131_4_fu_3688_p1 + zext_ln131_11_fu_3696_p1);

assign add_ln131_4_fu_3910_p2 = (zext_ln131_5_fu_3898_p1 + zext_ln131_12_fu_3906_p1);

assign add_ln131_5_fu_4120_p2 = (zext_ln131_6_fu_4108_p1 + zext_ln131_13_fu_4116_p1);

assign add_ln131_6_fu_4330_p2 = (zext_ln131_7_fu_4318_p1 + zext_ln131_14_fu_4326_p1);

assign add_ln131_7_fu_4568_p2 = (zext_ln131_8_fu_4556_p1 + zext_ln131_15_fu_4564_p1);

assign add_ln131_fu_3166_p2 = (zext_ln131_fu_3154_p1 + zext_ln131_1_fu_3162_p1);

assign add_ln132_1_fu_3356_p2 = (zext_ln132_2_fu_3344_p1 + zext_ln132_9_fu_3352_p1);

assign add_ln132_2_fu_3542_p2 = (zext_ln132_3_fu_3530_p1 + zext_ln132_10_fu_3538_p1);

assign add_ln132_3_fu_3728_p2 = (zext_ln132_4_fu_3716_p1 + zext_ln132_11_fu_3724_p1);

assign add_ln132_4_fu_3938_p2 = (zext_ln132_5_fu_3926_p1 + zext_ln132_12_fu_3934_p1);

assign add_ln132_5_fu_4148_p2 = (zext_ln132_6_fu_4136_p1 + zext_ln132_13_fu_4144_p1);

assign add_ln132_6_fu_4358_p2 = (zext_ln132_7_fu_4346_p1 + zext_ln132_14_fu_4354_p1);

assign add_ln132_7_fu_4596_p2 = (zext_ln132_8_fu_4584_p1 + zext_ln132_15_fu_4592_p1);

assign add_ln132_fu_3194_p2 = (zext_ln132_fu_3182_p1 + zext_ln132_1_fu_3190_p1);

assign add_ln144_fu_5352_p2 = (zext_ln144_1_fu_5348_p1 + zext_ln144_fu_5344_p1);

assign add_ln145_fu_5372_p2 = (zext_ln145_1_fu_5368_p1 + zext_ln145_fu_5364_p1);

assign add_ln146_fu_5392_p2 = (zext_ln146_1_fu_5388_p1 + zext_ln146_fu_5384_p1);

assign add_ln147_fu_5412_p2 = (zext_ln147_1_fu_5408_p1 + zext_ln147_fu_5404_p1);

assign add_ln148_fu_5432_p2 = (zext_ln148_1_fu_5428_p1 + zext_ln148_fu_5424_p1);

assign add_ln149_fu_5452_p2 = (zext_ln149_1_fu_5448_p1 + zext_ln149_fu_5444_p1);

assign add_ln150_fu_5472_p2 = (zext_ln150_1_fu_5468_p1 + zext_ln150_fu_5464_p1);

assign add_ln151_fu_5492_p2 = (zext_ln151_1_fu_5488_p1 + zext_ln151_fu_5484_p1);

assign add_ln47_fu_813_p2 = ($signed(sext_ln47_1_fu_809_p1) + $signed(sext_ln47_fu_801_p1));

assign add_ln52_1_fu_868_p2 = ($signed(sext_ln52_2_fu_856_p1) + $signed(sext_ln52_3_fu_864_p1));

assign add_ln52_fu_840_p2 = ($signed(sext_ln52_fu_828_p1) + $signed(sext_ln52_1_fu_836_p1));

assign add_ln60_1_fu_924_p2 = ($signed(sext_ln60_2_fu_912_p1) + $signed(sext_ln60_3_fu_920_p1));

assign add_ln60_2_fu_952_p2 = ($signed(zext_ln60_fu_940_p1) + $signed(sext_ln60_4_fu_948_p1));

assign add_ln60_3_fu_980_p2 = ($signed(zext_ln60_1_fu_968_p1) + $signed(sext_ln60_5_fu_976_p1));

assign add_ln60_fu_896_p2 = ($signed(sext_ln60_fu_884_p1) + $signed(sext_ln60_1_fu_892_p1));

assign add_ln69_1_fu_1036_p2 = ($signed(sext_ln69_2_fu_1024_p1) + $signed(sext_ln69_3_fu_1032_p1));

assign add_ln69_2_fu_1064_p2 = ($signed(sext_ln69_4_fu_1052_p1) + $signed(sext_ln69_5_fu_1060_p1));

assign add_ln69_3_fu_1092_p2 = ($signed(sext_ln69_6_fu_1080_p1) + $signed(sext_ln69_7_fu_1088_p1));

assign add_ln69_4_fu_1120_p2 = (zext_ln69_fu_1108_p1 + zext_ln69_1_fu_1116_p1);

assign add_ln69_5_fu_1148_p2 = ($signed(sext_ln69_8_fu_1136_p1) + $signed(zext_ln69_2_fu_1144_p1));

assign add_ln69_6_fu_1176_p2 = (zext_ln69_3_fu_1164_p1 + zext_ln69_4_fu_1172_p1);

assign add_ln69_7_fu_1204_p2 = ($signed(zext_ln69_5_fu_1192_p1) + $signed(sext_ln69_9_fu_1200_p1));

assign add_ln69_fu_1008_p2 = ($signed(sext_ln69_fu_996_p1) + $signed(sext_ln69_1_fu_1004_p1));

assign add_ln78_10_fu_1488_p2 = (zext_ln78_1_fu_1480_p1 + prod_5_2);

assign add_ln78_11_fu_1512_p2 = (prod_4_3 + trunc_ln78_fu_1508_p1);

assign add_ln78_12_fu_1536_p2 = (zext_ln78_2_fu_1528_p1 + prod_7_0);

assign add_ln78_13_fu_1560_p2 = (prod_6_1 + zext_ln78_3_fu_1556_p1);

assign add_ln78_14_fu_1584_p2 = (zext_ln78_4_fu_1576_p1 + prod_7_2);

assign add_ln78_15_fu_1612_p2 = ($signed(zext_ln78_5_fu_1600_p1) + $signed(sext_ln78_14_fu_1608_p1));

assign add_ln78_1_fu_1260_p2 = ($signed(sext_ln78_2_fu_1248_p1) + $signed(sext_ln78_3_fu_1256_p1));

assign add_ln78_2_fu_1288_p2 = ($signed(sext_ln78_4_fu_1276_p1) + $signed(sext_ln78_5_fu_1284_p1));

assign add_ln78_3_fu_1312_p2 = ($signed(prod_0_3) + $signed(sext_ln78_6_fu_1308_p1));

assign add_ln78_4_fu_1340_p2 = ($signed(sext_ln78_7_fu_1328_p1) + $signed(sext_ln78_8_fu_1336_p1));

assign add_ln78_5_fu_1368_p2 = ($signed(sext_ln78_9_fu_1356_p1) + $signed(sext_ln78_10_fu_1364_p1));

assign add_ln78_6_fu_1392_p2 = ($signed(prod_2_2) + $signed(sext_ln78_11_fu_1388_p1));

assign add_ln78_7_fu_1416_p2 = ($signed(prod_2_3) + $signed(sext_ln78_12_fu_1412_p1));

assign add_ln78_8_fu_1440_p2 = (zext_ln78_fu_1432_p1 + prod_5_0);

assign add_ln78_9_fu_1464_p2 = ($signed(sext_ln78_13_fu_1456_p1) + $signed(prod_5_1));

assign add_ln78_fu_1232_p2 = ($signed(sext_ln78_fu_1220_p1) + $signed(sext_ln78_1_fu_1228_p1));

assign add_ln86_1_fu_2045_p2 = (zext_ln86_24_fu_2029_p1 + zext_ln86_26_fu_2041_p1);

assign add_ln86_2_fu_2150_p2 = (zext_ln86_34_fu_2134_p1 + zext_ln86_35_fu_2146_p1);

assign add_ln86_fu_1977_p2 = (zext_ln86_20_fu_1961_p1 + zext_ln86_21_fu_1973_p1);

assign add_ln90_fu_2288_p2 = (zext_ln90_1_fu_2284_p1 + zext_ln90_fu_2276_p1);

assign add_ln91_fu_2316_p2 = (zext_ln91_1_fu_2312_p1 + zext_ln91_fu_2304_p1);

assign add_ln92_fu_2344_p2 = (zext_ln92_1_fu_2340_p1 + zext_ln92_fu_2332_p1);

assign add_ln93_fu_2372_p2 = (zext_ln93_1_fu_2368_p1 + zext_ln93_fu_2360_p1);

assign add_ln94_fu_2400_p2 = (zext_ln94_1_fu_2396_p1 + zext_ln94_fu_2388_p1);

assign add_ln95_fu_2428_p2 = (zext_ln95_1_fu_2424_p1 + zext_ln95_fu_2416_p1);

assign add_ln96_fu_2456_p2 = (zext_ln96_1_fu_2452_p1 + zext_ln96_fu_2444_p1);

assign add_ln97_fu_2484_p2 = (zext_ln97_1_fu_2480_p1 + zext_ln97_fu_2472_p1);

assign add_ln98_fu_2512_p2 = (zext_ln98_1_fu_2508_p1 + zext_ln98_fu_2500_p1);

assign add_ln99_fu_2540_p2 = (zext_ln99_1_fu_2536_p1 + zext_ln99_fu_2528_p1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign mul_ln86_10_fu_5580_p0 = 18'd262105;

assign mul_ln86_10_fu_5580_p1 = mul_ln86_10_fu_5580_p10;

assign mul_ln86_10_fu_5580_p10 = reg2_3_0;

assign mul_ln86_11_fu_5587_p0 = 18'd37;

assign mul_ln86_11_fu_5587_p1 = mul_ln86_11_fu_5587_p10;

assign mul_ln86_11_fu_5587_p10 = reg2_4_3;

assign mul_ln86_12_fu_5594_p0 = 18'd50;

assign mul_ln86_12_fu_5594_p1 = mul_ln86_12_fu_5594_p10;

assign mul_ln86_12_fu_5594_p10 = reg2_5_0;

assign mul_ln86_13_fu_5601_p0 = 18'd54;

assign mul_ln86_13_fu_5601_p1 = mul_ln86_13_fu_5601_p10;

assign mul_ln86_13_fu_5601_p10 = reg2_5_1;

assign mul_ln86_14_fu_5608_p0 = 17'd46;

assign mul_ln86_14_fu_5608_p1 = mul_ln86_14_fu_5608_p10;

assign mul_ln86_14_fu_5608_p10 = reg2_5_2;

assign mul_ln86_15_fu_5615_p0 = 19'd67;

assign mul_ln86_15_fu_5615_p1 = mul_ln86_15_fu_5615_p10;

assign mul_ln86_15_fu_5615_p10 = reg2_5_3;

assign mul_ln86_16_fu_5622_p0 = 19'd84;

assign mul_ln86_16_fu_5622_p1 = mul_ln86_16_fu_5622_p10;

assign mul_ln86_16_fu_5622_p10 = reg2_6_1;

assign mul_ln86_17_fu_5629_p0 = 18'd89;

assign mul_ln86_17_fu_5629_p1 = mul_ln86_17_fu_5629_p10;

assign mul_ln86_17_fu_5629_p10 = reg2_6_2;

assign mul_ln86_18_fu_5636_p0 = 19'd103;

assign mul_ln86_18_fu_5636_p1 = mul_ln86_18_fu_5636_p10;

assign mul_ln86_18_fu_5636_p10 = reg2_6_3;

assign mul_ln86_19_fu_5643_p0 = 19'd108;

assign mul_ln86_19_fu_5643_p1 = mul_ln86_19_fu_5643_p10;

assign mul_ln86_19_fu_5643_p10 = reg2_7_0;

assign mul_ln86_1_fu_5517_p0 = 19'd524198;

assign mul_ln86_1_fu_5517_p1 = mul_ln86_1_fu_5517_p10;

assign mul_ln86_1_fu_5517_p10 = reg2_0_1;

assign mul_ln86_20_fu_5650_p0 = 18'd117;

assign mul_ln86_20_fu_5650_p1 = mul_ln86_20_fu_5650_p10;

assign mul_ln86_20_fu_5650_p10 = reg2_7_1;

assign mul_ln86_21_fu_5657_p0 = 19'd122;

assign mul_ln86_21_fu_5657_p1 = mul_ln86_21_fu_5657_p10;

assign mul_ln86_21_fu_5657_p10 = reg2_7_2;

assign mul_ln86_2_fu_5524_p0 = 19'd524212;

assign mul_ln86_2_fu_5524_p1 = mul_ln86_2_fu_5524_p10;

assign mul_ln86_2_fu_5524_p10 = reg2_0_2;

assign mul_ln86_3_fu_5531_p0 = 19'd524221;

assign mul_ln86_3_fu_5531_p1 = mul_ln86_3_fu_5531_p10;

assign mul_ln86_3_fu_5531_p10 = reg2_0_3;

assign mul_ln86_4_fu_5538_p0 = 19'd524190;

assign mul_ln86_4_fu_5538_p1 = mul_ln86_4_fu_5538_p10;

assign mul_ln86_4_fu_5538_p10 = reg2_1_1;

assign mul_ln86_5_fu_5545_p0 = 19'd524215;

assign mul_ln86_5_fu_5545_p1 = mul_ln86_5_fu_5545_p10;

assign mul_ln86_5_fu_5545_p10 = reg2_1_2;

assign mul_ln86_6_fu_5552_p0 = 18'd262092;

assign mul_ln86_6_fu_5552_p1 = mul_ln86_6_fu_5552_p10;

assign mul_ln86_6_fu_5552_p10 = reg2_1_3;

assign mul_ln86_7_fu_5559_p0 = 17'd131046;

assign mul_ln86_7_fu_5559_p1 = mul_ln86_7_fu_5559_p10;

assign mul_ln86_7_fu_5559_p10 = reg2_2_1;

assign mul_ln86_8_fu_5566_p0 = 17'd131050;

assign mul_ln86_8_fu_5566_p1 = mul_ln86_8_fu_5566_p10;

assign mul_ln86_8_fu_5566_p10 = reg2_2_2;

assign mul_ln86_9_fu_5573_p0 = 18'd262077;

assign mul_ln86_9_fu_5573_p1 = mul_ln86_9_fu_5573_p10;

assign mul_ln86_9_fu_5573_p10 = reg2_2_3;

assign mul_ln86_fu_5510_p0 = 19'd524182;

assign mul_ln86_fu_5510_p1 = mul_ln86_fu_5510_p10;

assign mul_ln86_fu_5510_p10 = reg2_0_0;

assign out_r = $signed(add_ln47_fu_813_p2);

assign sext_ln47_1_fu_809_p0 = sum_l3_1;

assign sext_ln47_1_fu_809_p1 = sext_ln47_1_fu_809_p0;

assign sext_ln47_fu_801_p0 = sum_l3_0;

assign sext_ln47_fu_801_p1 = sext_ln47_fu_801_p0;

assign sext_ln52_1_fu_836_p0 = sum_l2_0_1;

assign sext_ln52_1_fu_836_p1 = sext_ln52_1_fu_836_p0;

assign sext_ln52_2_fu_856_p0 = sum_l2_1_0;

assign sext_ln52_2_fu_856_p1 = sext_ln52_2_fu_856_p0;

assign sext_ln52_3_fu_864_p0 = sum_l2_1_1;

assign sext_ln52_3_fu_864_p1 = sext_ln52_3_fu_864_p0;

assign sext_ln52_fu_828_p0 = sum_l2_0_0;

assign sext_ln52_fu_828_p1 = sext_ln52_fu_828_p0;

assign sext_ln60_1_fu_892_p0 = sum_l1_0_1;

assign sext_ln60_1_fu_892_p1 = sext_ln60_1_fu_892_p0;

assign sext_ln60_2_fu_912_p0 = sum_l1_0_2;

assign sext_ln60_2_fu_912_p1 = sext_ln60_2_fu_912_p0;

assign sext_ln60_3_fu_920_p0 = sum_l1_0_3;

assign sext_ln60_3_fu_920_p1 = sext_ln60_3_fu_920_p0;

assign sext_ln60_4_fu_948_p0 = sum_l1_1_1;

assign sext_ln60_4_fu_948_p1 = sext_ln60_4_fu_948_p0;

assign sext_ln60_5_fu_976_p0 = sum_l1_1_3;

assign sext_ln60_5_fu_976_p1 = sext_ln60_5_fu_976_p0;

assign sext_ln60_fu_884_p0 = sum_l1_0_0;

assign sext_ln60_fu_884_p1 = sext_ln60_fu_884_p0;

assign sext_ln69_1_fu_1004_p0 = sum_l0_1_0;

assign sext_ln69_1_fu_1004_p1 = sext_ln69_1_fu_1004_p0;

assign sext_ln69_2_fu_1024_p0 = sum_l0_0_1;

assign sext_ln69_2_fu_1024_p1 = sext_ln69_2_fu_1024_p0;

assign sext_ln69_3_fu_1032_p0 = sum_l0_1_1;

assign sext_ln69_3_fu_1032_p1 = sext_ln69_3_fu_1032_p0;

assign sext_ln69_4_fu_1052_p0 = sum_l0_0_2;

assign sext_ln69_4_fu_1052_p1 = sext_ln69_4_fu_1052_p0;

assign sext_ln69_5_fu_1060_p0 = sum_l0_1_2;

assign sext_ln69_5_fu_1060_p1 = sext_ln69_5_fu_1060_p0;

assign sext_ln69_6_fu_1080_p0 = sum_l0_0_3;

assign sext_ln69_6_fu_1080_p1 = sext_ln69_6_fu_1080_p0;

assign sext_ln69_7_fu_1088_p0 = sum_l0_1_3;

assign sext_ln69_7_fu_1088_p1 = sext_ln69_7_fu_1088_p0;

assign sext_ln69_8_fu_1136_p0 = sum_l0_2_1;

assign sext_ln69_8_fu_1136_p1 = sext_ln69_8_fu_1136_p0;

assign sext_ln69_9_fu_1200_p0 = sum_l0_3_3;

assign sext_ln69_9_fu_1200_p1 = sext_ln69_9_fu_1200_p0;

assign sext_ln69_fu_996_p0 = sum_l0_0_0;

assign sext_ln69_fu_996_p1 = sext_ln69_fu_996_p0;

assign sext_ln78_10_fu_1364_p0 = prod_3_1;

assign sext_ln78_10_fu_1364_p1 = sext_ln78_10_fu_1364_p0;

assign sext_ln78_11_fu_1388_p0 = prod_3_2;

assign sext_ln78_11_fu_1388_p1 = sext_ln78_11_fu_1388_p0;

assign sext_ln78_12_fu_1412_p0 = prod_3_3;

assign sext_ln78_12_fu_1412_p1 = sext_ln78_12_fu_1412_p0;

assign sext_ln78_13_fu_1456_p0 = prod_4_1;

assign sext_ln78_13_fu_1456_p1 = sext_ln78_13_fu_1456_p0;

assign sext_ln78_14_fu_1608_p0 = prod_7_3;

assign sext_ln78_14_fu_1608_p1 = sext_ln78_14_fu_1608_p0;

assign sext_ln78_1_fu_1228_p0 = prod_1_0;

assign sext_ln78_1_fu_1228_p1 = sext_ln78_1_fu_1228_p0;

assign sext_ln78_2_fu_1248_p0 = prod_0_1;

assign sext_ln78_2_fu_1248_p1 = sext_ln78_2_fu_1248_p0;

assign sext_ln78_3_fu_1256_p0 = prod_1_1;

assign sext_ln78_3_fu_1256_p1 = sext_ln78_3_fu_1256_p0;

assign sext_ln78_4_fu_1276_p0 = prod_0_2;

assign sext_ln78_4_fu_1276_p1 = sext_ln78_4_fu_1276_p0;

assign sext_ln78_5_fu_1284_p0 = prod_1_2;

assign sext_ln78_5_fu_1284_p1 = sext_ln78_5_fu_1284_p0;

assign sext_ln78_6_fu_1308_p0 = prod_1_3;

assign sext_ln78_6_fu_1308_p1 = sext_ln78_6_fu_1308_p0;

assign sext_ln78_7_fu_1328_p0 = prod_2_0;

assign sext_ln78_7_fu_1328_p1 = sext_ln78_7_fu_1328_p0;

assign sext_ln78_8_fu_1336_p0 = prod_3_0;

assign sext_ln78_8_fu_1336_p1 = sext_ln78_8_fu_1336_p0;

assign sext_ln78_9_fu_1356_p0 = prod_2_1;

assign sext_ln78_9_fu_1356_p1 = sext_ln78_9_fu_1356_p0;

assign sext_ln78_fu_1220_p0 = prod_0_0;

assign sext_ln78_fu_1220_p1 = sext_ln78_fu_1220_p0;

assign sext_ln86_fu_1765_p1 = $signed(sub_ln86_1_fu_1759_p2);

assign shl_ln86_10_fu_2126_p3 = {{reg2_6_0}, {6'd0}};

assign shl_ln86_11_fu_2138_p3 = {{reg2_6_0}, {4'd0}};

assign shl_ln86_1_fu_1747_p3 = {{reg2_2_0}, {5'd0}};

assign shl_ln86_2_fu_1769_p3 = {{reg2_2_0}, {2'd0}};

assign shl_ln86_3_fu_1885_p3 = {{reg2_3_2}, {2'd0}};

assign shl_ln86_4_fu_1913_p3 = {{reg2_3_3}, {4'd0}};

assign shl_ln86_5_fu_1925_p3 = {{reg2_3_3}, {1'd0}};

assign shl_ln86_6_fu_1953_p3 = {{reg2_4_0}, {4'd0}};

assign shl_ln86_7_fu_1965_p3 = {{reg2_4_0}, {1'd0}};

assign shl_ln86_8_fu_1993_p3 = {{reg2_4_1}, {3'd0}};

assign shl_ln86_9_fu_2021_p3 = {{reg2_4_2}, {4'd0}};

assign shl_ln86_s_fu_2033_p3 = {{reg2_4_2}, {1'd0}};

assign shl_ln_fu_1680_p3 = {{reg2_1_0}, {6'd0}};

assign sub_ln86_1_fu_1759_p2 = (17'd0 - zext_ln86_8_fu_1755_p1);

assign sub_ln86_2_fu_1781_p2 = ($signed(sext_ln86_fu_1765_p1) - $signed(zext_ln86_9_fu_1777_p1));

assign sub_ln86_3_fu_1897_p2 = (zext_ln86_17_fu_1893_p1 - zext_ln86_16_fu_1881_p1);

assign sub_ln86_4_fu_1937_p2 = (zext_ln86_18_fu_1921_p1 - zext_ln86_19_fu_1933_p1);

assign sub_ln86_5_fu_2005_p2 = (14'd0 - zext_ln86_22_fu_2001_p1);

assign sub_ln86_6_fu_2260_p2 = (zext_ln86_39_fu_2256_p1 - zext_ln86_38_fu_2244_p1);

assign sub_ln86_7_fu_1865_p2 = (zext_ln86_14_fu_1849_p1 - zext_ln86_15_fu_1861_p1);

assign sub_ln86_fu_1692_p2 = (18'd0 - zext_ln86_4_fu_1688_p1);

assign tmp_1_fu_2248_p3 = {{reg2_7_3}, {7'd0}};

assign tmp_fu_1853_p3 = {{reg2_3_1}, {4'd0}};

assign trunc_ln78_fu_1508_p1 = prod_5_3[17:0];

assign zext_ln100_1_fu_2564_p1 = reg1_8_2;

assign zext_ln100_fu_2556_p1 = reg1_2_8;

assign zext_ln102_1_fu_2602_p1 = reg1_4_3;

assign zext_ln102_fu_2594_p1 = reg1_3_4;

assign zext_ln103_1_fu_2630_p1 = reg1_5_3;

assign zext_ln103_fu_2622_p1 = reg1_3_5;

assign zext_ln104_1_fu_2658_p1 = reg1_6_3;

assign zext_ln104_fu_2650_p1 = reg1_3_6;

assign zext_ln105_1_fu_2686_p1 = reg1_7_3;

assign zext_ln105_fu_2678_p1 = reg1_3_7;

assign zext_ln106_1_fu_2714_p1 = reg1_8_3;

assign zext_ln106_fu_2706_p1 = reg1_3_8;

assign zext_ln108_1_fu_2752_p1 = reg1_5_4;

assign zext_ln108_fu_2744_p1 = reg1_4_5;

assign zext_ln109_1_fu_2780_p1 = reg1_6_4;

assign zext_ln109_fu_2772_p1 = reg1_4_6;

assign zext_ln110_1_fu_2808_p1 = reg1_7_4;

assign zext_ln110_fu_2800_p1 = reg1_4_7;

assign zext_ln111_1_fu_2836_p1 = reg1_8_4;

assign zext_ln111_fu_2828_p1 = reg1_4_8;

assign zext_ln113_1_fu_2874_p1 = reg1_6_5;

assign zext_ln113_fu_2866_p1 = reg1_5_6;

assign zext_ln114_1_fu_2902_p1 = reg1_7_5;

assign zext_ln114_fu_2894_p1 = reg1_5_7;

assign zext_ln115_1_fu_2930_p1 = reg1_8_5;

assign zext_ln115_fu_2922_p1 = reg1_5_8;

assign zext_ln117_1_fu_2968_p1 = reg1_7_6;

assign zext_ln117_fu_2960_p1 = reg1_6_7;

assign zext_ln118_1_fu_2996_p1 = reg1_8_6;

assign zext_ln118_fu_2988_p1 = reg1_6_8;

assign zext_ln120_1_fu_3034_p1 = reg1_8_7;

assign zext_ln120_fu_3026_p1 = reg1_7_8;

assign zext_ln125_1_fu_4392_p1 = reg0_8_16;

assign zext_ln125_fu_4384_p1 = reg0_8_0;

assign zext_ln126_1_fu_3766_p1 = reg0_5_15;

assign zext_ln126_2_fu_3968_p1 = reg0_6_1;

assign zext_ln126_3_fu_3976_p1 = reg0_6_15;

assign zext_ln126_4_fu_4178_p1 = reg0_7_1;

assign zext_ln126_5_fu_4186_p1 = reg0_7_15;

assign zext_ln126_6_fu_4412_p1 = reg0_8_1;

assign zext_ln126_7_fu_4420_p1 = reg0_8_15;

assign zext_ln126_fu_3758_p1 = reg0_5_1;

assign zext_ln127_10_fu_4214_p1 = reg0_7_14;

assign zext_ln127_11_fu_4448_p1 = reg0_8_14;

assign zext_ln127_1_fu_3398_p1 = reg0_3_14;

assign zext_ln127_2_fu_3576_p1 = reg0_4_2;

assign zext_ln127_3_fu_3584_p1 = reg0_4_14;

assign zext_ln127_4_fu_3786_p1 = reg0_5_2;

assign zext_ln127_5_fu_3794_p1 = reg0_5_14;

assign zext_ln127_6_fu_3996_p1 = reg0_6_2;

assign zext_ln127_7_fu_4206_p1 = reg0_7_2;

assign zext_ln127_8_fu_4440_p1 = reg0_8_2;

assign zext_ln127_9_fu_4004_p1 = reg0_6_14;

assign zext_ln127_fu_3390_p1 = reg0_3_2;

assign zext_ln128_10_fu_3822_p1 = reg0_5_13;

assign zext_ln128_11_fu_4032_p1 = reg0_6_13;

assign zext_ln128_12_fu_4242_p1 = reg0_7_13;

assign zext_ln128_13_fu_4480_p1 = reg0_8_13;

assign zext_ln128_14_fu_4468_p1 = reg0_8_3;

assign zext_ln128_1_fu_3240_p1 = reg0_2_13;

assign zext_ln128_2_fu_3418_p1 = reg0_3_3;

assign zext_ln128_3_fu_3426_p1 = reg0_3_13;

assign zext_ln128_4_fu_3604_p1 = reg0_4_3;

assign zext_ln128_5_fu_3814_p1 = reg0_5_3;

assign zext_ln128_6_fu_4024_p1 = reg0_6_3;

assign zext_ln128_7_fu_4234_p1 = reg0_7_3;

assign zext_ln128_8_fu_4472_p1 = reg0_8_3;

assign zext_ln128_9_fu_3612_p1 = reg0_4_13;

assign zext_ln128_fu_3232_p1 = reg0_2_3;

assign zext_ln129_10_fu_3850_p1 = reg0_5_12;

assign zext_ln129_11_fu_4060_p1 = reg0_6_12;

assign zext_ln129_12_fu_4270_p1 = reg0_7_12;

assign zext_ln129_13_fu_4508_p1 = reg0_8_12;

assign zext_ln129_1_fu_3268_p1 = reg0_2_12;

assign zext_ln129_2_fu_3446_p1 = reg0_3_4;

assign zext_ln129_3_fu_3454_p1 = reg0_3_12;

assign zext_ln129_4_fu_3632_p1 = reg0_4_4;

assign zext_ln129_5_fu_3842_p1 = reg0_5_4;

assign zext_ln129_6_fu_4052_p1 = reg0_6_4;

assign zext_ln129_7_fu_4262_p1 = reg0_7_4;

assign zext_ln129_8_fu_4500_p1 = reg0_8_4;

assign zext_ln129_9_fu_3640_p1 = reg0_4_12;

assign zext_ln129_fu_3260_p1 = reg0_2_4;

assign zext_ln130_10_fu_3482_p1 = reg0_3_11;

assign zext_ln130_11_fu_3668_p1 = reg0_4_11;

assign zext_ln130_12_fu_3878_p1 = reg0_5_11;

assign zext_ln130_13_fu_4088_p1 = reg0_6_11;

assign zext_ln130_14_fu_4298_p1 = reg0_7_11;

assign zext_ln130_15_fu_4536_p1 = reg0_8_11;

assign zext_ln130_1_fu_3134_p1 = reg0_1_11;

assign zext_ln130_2_fu_3288_p1 = reg0_2_5;

assign zext_ln130_3_fu_3474_p1 = reg0_3_5;

assign zext_ln130_4_fu_3660_p1 = reg0_4_5;

assign zext_ln130_5_fu_3870_p1 = reg0_5_5;

assign zext_ln130_6_fu_4080_p1 = reg0_6_5;

assign zext_ln130_7_fu_4290_p1 = reg0_7_5;

assign zext_ln130_8_fu_4528_p1 = reg0_8_5;

assign zext_ln130_9_fu_3296_p1 = reg0_2_11;

assign zext_ln130_fu_3126_p1 = reg0_1_5;

assign zext_ln131_10_fu_3510_p1 = reg0_3_10;

assign zext_ln131_11_fu_3696_p1 = reg0_4_10;

assign zext_ln131_12_fu_3906_p1 = reg0_5_10;

assign zext_ln131_13_fu_4116_p1 = reg0_6_10;

assign zext_ln131_14_fu_4326_p1 = reg0_7_10;

assign zext_ln131_15_fu_4564_p1 = reg0_8_10;

assign zext_ln131_1_fu_3162_p1 = reg0_1_10;

assign zext_ln131_2_fu_3316_p1 = reg0_2_6;

assign zext_ln131_3_fu_3502_p1 = reg0_3_6;

assign zext_ln131_4_fu_3688_p1 = reg0_4_6;

assign zext_ln131_5_fu_3898_p1 = reg0_5_6;

assign zext_ln131_6_fu_4108_p1 = reg0_6_6;

assign zext_ln131_7_fu_4318_p1 = reg0_7_6;

assign zext_ln131_8_fu_4556_p1 = reg0_8_6;

assign zext_ln131_9_fu_3324_p1 = reg0_2_10;

assign zext_ln131_fu_3154_p1 = reg0_1_6;

assign zext_ln132_10_fu_3538_p1 = reg0_3_9;

assign zext_ln132_11_fu_3724_p1 = reg0_4_9;

assign zext_ln132_12_fu_3934_p1 = reg0_5_9;

assign zext_ln132_13_fu_4144_p1 = reg0_6_9;

assign zext_ln132_14_fu_4354_p1 = reg0_7_9;

assign zext_ln132_15_fu_4592_p1 = reg0_8_9;

assign zext_ln132_1_fu_3190_p1 = reg0_1_9;

assign zext_ln132_2_fu_3344_p1 = reg0_2_7;

assign zext_ln132_3_fu_3530_p1 = reg0_3_7;

assign zext_ln132_4_fu_3716_p1 = reg0_4_7;

assign zext_ln132_5_fu_3926_p1 = reg0_5_7;

assign zext_ln132_6_fu_4136_p1 = reg0_6_7;

assign zext_ln132_7_fu_4346_p1 = reg0_7_7;

assign zext_ln132_8_fu_4584_p1 = reg0_8_7;

assign zext_ln132_9_fu_3352_p1 = reg0_2_9;

assign zext_ln132_fu_3182_p1 = reg0_1_7;

assign zext_ln144_1_fu_5348_p1 = in16;

assign zext_ln144_fu_5344_p1 = in0;

assign zext_ln145_1_fu_5368_p1 = in15;

assign zext_ln145_fu_5364_p1 = in1;

assign zext_ln146_1_fu_5388_p1 = in14;

assign zext_ln146_fu_5384_p1 = in2;

assign zext_ln147_1_fu_5408_p1 = in13;

assign zext_ln147_fu_5404_p1 = in3;

assign zext_ln148_1_fu_5428_p1 = in12;

assign zext_ln148_fu_5424_p1 = in4;

assign zext_ln149_1_fu_5448_p1 = in11;

assign zext_ln149_fu_5444_p1 = in5;

assign zext_ln150_1_fu_5468_p1 = in10;

assign zext_ln150_fu_5464_p1 = in6;

assign zext_ln151_1_fu_5488_p1 = in9;

assign zext_ln151_fu_5484_p1 = in7;

assign zext_ln60_1_fu_968_p1 = sum_l1_1_2;

assign zext_ln60_fu_940_p1 = sum_l1_1_0;

assign zext_ln69_1_fu_1116_p1 = sum_l0_3_0;

assign zext_ln69_2_fu_1144_p1 = sum_l0_3_1;

assign zext_ln69_3_fu_1164_p1 = sum_l0_2_2;

assign zext_ln69_4_fu_1172_p1 = sum_l0_3_2;

assign zext_ln69_5_fu_1192_p1 = sum_l0_2_3;

assign zext_ln69_fu_1108_p1 = sum_l0_2_0;

assign zext_ln78_1_fu_1480_p1 = prod_4_2;

assign zext_ln78_2_fu_1528_p1 = prod_6_0;

assign zext_ln78_3_fu_1556_p1 = prod_7_1;

assign zext_ln78_4_fu_1576_p1 = prod_6_2;

assign zext_ln78_5_fu_1600_p1 = prod_6_3;

assign zext_ln78_fu_1432_p1 = prod_4_0;

assign zext_ln86_14_fu_1849_p1 = reg2_3_1;

assign zext_ln86_15_fu_1861_p1 = tmp_fu_1853_p3;

assign zext_ln86_16_fu_1881_p1 = reg2_3_2;

assign zext_ln86_17_fu_1893_p1 = shl_ln86_3_fu_1885_p3;

assign zext_ln86_18_fu_1921_p1 = shl_ln86_4_fu_1913_p3;

assign zext_ln86_19_fu_1933_p1 = shl_ln86_5_fu_1925_p3;

assign zext_ln86_20_fu_1961_p1 = shl_ln86_6_fu_1953_p3;

assign zext_ln86_21_fu_1973_p1 = shl_ln86_7_fu_1965_p3;

assign zext_ln86_22_fu_2001_p1 = shl_ln86_8_fu_1993_p3;

assign zext_ln86_24_fu_2029_p1 = shl_ln86_9_fu_2021_p3;

assign zext_ln86_26_fu_2041_p1 = shl_ln86_s_fu_2033_p3;

assign zext_ln86_34_fu_2134_p1 = shl_ln86_10_fu_2126_p3;

assign zext_ln86_35_fu_2146_p1 = shl_ln86_11_fu_2138_p3;

assign zext_ln86_38_fu_2244_p1 = reg2_7_3;

assign zext_ln86_39_fu_2256_p1 = tmp_1_fu_2248_p3;

assign zext_ln86_4_fu_1688_p1 = shl_ln_fu_1680_p3;

assign zext_ln86_8_fu_1755_p1 = shl_ln86_1_fu_1747_p3;

assign zext_ln86_9_fu_1777_p1 = shl_ln86_2_fu_1769_p3;

assign zext_ln90_1_fu_2284_p1 = reg1_8_0;

assign zext_ln90_fu_2276_p1 = reg1_0_8;

assign zext_ln91_1_fu_2312_p1 = reg1_5_1;

assign zext_ln91_fu_2304_p1 = reg1_1_5;

assign zext_ln92_1_fu_2340_p1 = reg1_6_1;

assign zext_ln92_fu_2332_p1 = reg1_1_6;

assign zext_ln93_1_fu_2368_p1 = reg1_7_1;

assign zext_ln93_fu_2360_p1 = reg1_1_7;

assign zext_ln94_1_fu_2396_p1 = reg1_8_1;

assign zext_ln94_fu_2388_p1 = reg1_1_8;

assign zext_ln95_1_fu_2424_p1 = reg1_3_2;

assign zext_ln95_fu_2416_p1 = reg1_2_3;

assign zext_ln96_1_fu_2452_p1 = reg1_4_2;

assign zext_ln96_fu_2444_p1 = reg1_2_4;

assign zext_ln97_1_fu_2480_p1 = reg1_5_2;

assign zext_ln97_fu_2472_p1 = reg1_2_5;

assign zext_ln98_1_fu_2508_p1 = reg1_6_2;

assign zext_ln98_fu_2500_p1 = reg1_2_6;

assign zext_ln99_1_fu_2536_p1 = reg1_7_2;

assign zext_ln99_fu_2528_p1 = reg1_2_7;

always @ (posedge ap_clk) begin
    prod_1_0[5:0] <= 6'b000000;
    prod_2_0[1:0] <= 2'b00;
    prod_3_3[0] <= 1'b0;
    prod_4_0[0] <= 1'b0;
    prod_4_1[2:0] <= 3'b000;
    prod_4_2[0] <= 1'b0;
    prod_6_0[3:0] <= 4'b0000;
    reg2_7_3[8] <= 1'b0;
    reg1_8_8[8] <= 1'b0;
    reg0_8_16[8] <= 1'b0;
    reg0_8_15[8] <= 1'b0;
    reg0_8_14[8] <= 1'b0;
    reg0_8_13[8] <= 1'b0;
    reg0_8_4[8] <= 1'b0;
    reg0_8_12[8] <= 1'b0;
    reg0_8_5[8] <= 1'b0;
    reg0_8_11[8] <= 1'b0;
    reg0_8_6[8] <= 1'b0;
    reg0_8_10[8] <= 1'b0;
    reg0_8_7[8] <= 1'b0;
    reg0_8_9[8] <= 1'b0;
    reg0_8_8[8] <= 1'b0;
end

endmodule //filter_accel
